//   /** ISO 3166-1 A2 code. */
//   code: string;
//   /** ISO 3166-1 A3 code. */
//   triple_code: string;
//   /** ISO 3166-1 Numeric code. */
//   numeric_code: "number";
//   /** ISO 3166-2 subdivision codes link */
//   code_link: string;
//   /** Top level domain (TLD) */
//   domain: string;

import { country_paths } from './country_paths';

const country_data = [
  {
    name: 'Afghanistan',
    official_name: 'the Islamic Republic of Afghanistan[b]',
    sovereignty: 'UN member',
    code: 'AF',
    triple_code: 'AFG',
    numeric_code: '4',
    code_link: 'ISO 3166-2:AF',
    domain: '.af',
  },
  // {
  //   name: 'Åland Islands',
  //   official_name: 'Åland[c][d]',
  //   sovereignty: 'Finland',
  //   code: 'AX',
  //   triple_code: 'ALA',
  //   numeric_code: '248',
  //   code_link: 'ISO 3166-2:AX',
  //   domain: '.ax',
  // },
  {
    name: 'Albania',
    official_name: 'the Republic of Albania',
    sovereignty: 'UN member',
    code: 'AL',
    triple_code: 'ALB',
    numeric_code: '8',
    code_link: 'ISO 3166-2:AL',
    domain: '.al',
  },
  {
    name: 'Algeria',
    official_name: "the People's Democratic Republic of Algeria",
    sovereignty: 'UN member',
    code: 'DZ',
    triple_code: 'DZA',
    numeric_code: '12',
    code_link: 'ISO 3166-2:DZ',
    domain: '.dz',
  },
  // {
  //   name: 'American Samoa',
  //   official_name: 'American Samoa[c]',
  //   sovereignty: 'United States',
  //   code: 'AS',
  //   triple_code: 'ASM',
  //   numeric_code: '16',
  //   code_link: 'ISO 3166-2:AS',
  //   domain: '.as',
  // },
  {
    name: 'Andorra',
    official_name: 'the Principality of Andorra',
    sovereignty: 'UN member',
    code: 'AD',
    triple_code: 'AND',
    numeric_code: '20',
    code_link: 'ISO 3166-2:AD',
    domain: '.ad',
  },
  {
    name: 'Angola',
    official_name: 'the Republic of Angola',
    sovereignty: 'UN member',
    code: 'AO',
    triple_code: 'AGO',
    numeric_code: '24',
    code_link: 'ISO 3166-2:AO',
    domain: '.ao',
  },
  {
    name: 'Anguilla',
    official_name: 'Anguilla[c]',
    sovereignty: 'United Kingdom',
    code: 'AI',
    triple_code: 'AIA',
    numeric_code: '660',
    code_link: 'ISO 3166-2:AI',
    domain: '.ai',
  },
  // {
  //   name: 'Antarctica[e]',
  //   official_name: 'Antarctica[c]',
  //   sovereignty: 'Antarctic Treaty',
  //   code: 'AQ',
  //   triple_code: 'ATA',
  //   numeric_code: '10',
  //   code_link: 'ISO 3166-2:AQ',
  //   domain: '.aq',
  // },
  {
    name: 'Antigua and Barbuda',
    official_name: 'Antigua and Barbuda[c]',
    sovereignty: 'UN member',
    code: 'AG',
    triple_code: 'ATG',
    numeric_code: '28',
    code_link: 'ISO 3166-2:AG',
    domain: '.ag',
  },
  {
    name: 'Argentina',
    official_name: 'the Argentine Republic',
    sovereignty: 'UN member',
    code: 'AR',
    triple_code: 'ARG',
    numeric_code: '32',
    code_link: 'ISO 3166-2:AR',
    domain: '.ar',
  },
  {
    name: 'Armenia',
    official_name: 'the Republic of Armenia',
    sovereignty: 'UN member',
    code: 'AM',
    triple_code: 'ARM',
    numeric_code: '51',
    code_link: 'ISO 3166-2:AM',
    domain: '.am',
  },
  {
    name: 'Aruba',
    official_name: 'the Country of Aruba[c]',
    sovereignty: 'Netherlands',
    code: 'AW',
    triple_code: 'ABW',
    numeric_code: '533',
    code_link: 'ISO 3166-2:AW',
    domain: '.aw',
  },
  {
    name: 'Australia[f]',
    official_name: 'the Commonwealth of Australia[c]',
    sovereignty: 'UN member',
    code: 'AU',
    triple_code: 'AUS',
    numeric_code: '36',
    code_link: 'ISO 3166-2:AU',
    domain: '.au',
  },
  {
    name: 'Austria',
    official_name: 'the Republic of Austria',
    sovereignty: 'UN member',
    code: 'AT',
    triple_code: 'AUT',
    numeric_code: '40',
    code_link: 'ISO 3166-2:AT',
    domain: '.at',
  },
  {
    name: 'Azerbaijan',
    official_name: 'the Republic of Azerbaijan',
    sovereignty: 'UN member',
    code: 'AZ',
    triple_code: 'AZE',
    numeric_code: '31',
    code_link: 'ISO 3166-2:AZ',
    domain: '.az',
  },
  {
    name: 'Bahamas (the)',
    official_name: 'the Commonwealth of The Bahamas',
    sovereignty: 'UN member',
    code: 'BS',
    triple_code: 'BHS',
    numeric_code: '44',
    code_link: 'ISO 3166-2:BS',
    domain: '.bs',
  },
  {
    name: 'Bahrain',
    official_name: 'the Kingdom of Bahrain',
    sovereignty: 'UN member',
    code: 'BH',
    triple_code: 'BHR',
    numeric_code: '48',
    code_link: 'ISO 3166-2:BH',
    domain: '.bh',
  },
  {
    name: 'Bangladesh',
    official_name: "the People's Republic of Bangladesh",
    sovereignty: 'UN member',
    code: 'BD',
    triple_code: 'BGD',
    numeric_code: '50',
    code_link: 'ISO 3166-2:BD',
    domain: '.bd',
  },
  {
    name: 'Barbados',
    official_name: 'Barbados[c]',
    sovereignty: 'UN member',
    code: 'BB',
    triple_code: 'BRB',
    numeric_code: '52',
    code_link: 'ISO 3166-2:BB',
    domain: '.bb',
  },
  {
    name: 'Belarus',
    official_name: 'the Republic of Belarus',
    sovereignty: 'UN member',
    code: 'BY',
    triple_code: 'BLR',
    numeric_code: '112',
    code_link: 'ISO 3166-2:BY',
    domain: '.by',
  },
  {
    name: 'Belgium',
    official_name: 'the Kingdom of Belgium',
    sovereignty: 'UN member',
    code: 'BE',
    triple_code: 'BEL',
    numeric_code: '56',
    code_link: 'ISO 3166-2:BE',
    domain: '.be',
  },
  {
    name: 'Belize',
    official_name: 'Belize[c]',
    sovereignty: 'UN member',
    code: 'BZ',
    triple_code: 'BLZ',
    numeric_code: '84',
    code_link: 'ISO 3166-2:BZ',
    domain: '.bz',
  },
  {
    name: 'Benin',
    official_name: 'the Republic of Benin',
    sovereignty: 'UN member',
    code: 'BJ',
    triple_code: 'BEN',
    numeric_code: '204',
    code_link: 'ISO 3166-2:BJ',
    domain: '.bj',
  },
  {
    name: 'Bermuda',
    official_name: 'Bermuda[c]',
    sovereignty: 'United Kingdom',
    code: 'BM',
    triple_code: 'BMU',
    numeric_code: '60',
    code_link: 'ISO 3166-2:BM',
    domain: '.bm',
  },
  {
    name: 'Bhutan',
    official_name: 'the Kingdom of Bhutan',
    sovereignty: 'UN member',
    code: 'BT',
    triple_code: 'BTN',
    numeric_code: '64',
    code_link: 'ISO 3166-2:BT',
    domain: '.bt',
  },
  {
    name: 'Bolivia (Plurinational State of)',
    official_name: 'the Plurinational State of Bolivia',
    sovereignty: 'UN member',
    code: 'BO',
    triple_code: 'BOL',
    numeric_code: '68',
    code_link: 'ISO 3166-2:BO',
    domain: '.bo',
  },
  // {
  //   name: '- Bonaire\n   - Sint Eustatius\n   - Saba',
  //   official_name: 'Bonaire, Sint Eustatius and Saba[c][d]',
  //   sovereignty: 'Netherlands',
  //   code: 'BQ',
  //   triple_code: 'BES',
  //   numeric_code: '535',
  //   code_link: 'ISO 3166-2:BQ',
  //   domain: '- .bq\n   - .nl[g]',
  // },
  {
    name: 'Bosnia and Herzegovina',
    official_name: 'Bosnia and Herzegovina[c]',
    sovereignty: 'UN member',
    code: 'BA',
    triple_code: 'BIH',
    numeric_code: '70',
    code_link: 'ISO 3166-2:BA',
    domain: '.ba',
  },
  {
    name: 'Botswana',
    official_name: 'the Republic of Botswana',
    sovereignty: 'UN member',
    code: 'BW',
    triple_code: 'BWA',
    numeric_code: '72',
    code_link: 'ISO 3166-2:BW',
    domain: '.bw',
  },
  // {
  //   name: 'Bouvet Island',
  //   official_name: 'Bouvet Island[c]',
  //   sovereignty: 'Norway',
  //   code: 'BV',
  //   triple_code: 'BVT',
  //   numeric_code: '74',
  //   code_link: 'ISO 3166-2:BV',
  //   domain: '[h]',
  // },
  {
    name: 'Brazil',
    official_name: 'the Federative Republic of Brazil',
    sovereignty: 'UN member',
    code: 'BR',
    triple_code: 'BRA',
    numeric_code: '76',
    code_link: 'ISO 3166-2:BR',
    domain: '.br',
  },
  // {
  //   name: 'British Indian Ocean Territory (the)',
  //   official_name: 'the British Indian Ocean Territory[c]',
  //   sovereignty: 'United Kingdom',
  //   code: 'IO',
  //   triple_code: 'IOT',
  //   numeric_code: '86',
  //   code_link: 'ISO 3166-2:IO',
  //   domain: '.io',
  // },
  {
    name: 'British Virgin Islands – See Virgin Islands (British).',
    official_name: '',
    sovereignty: '',
    code: '',
    triple_code: '',
    numeric_code: "''",
    code_link: '',
    domain: '',
  },
  {
    name: 'Brunei Darussalam[i]',
    official_name: 'Brunei Darussalam[c]',
    sovereignty: 'UN member',
    code: 'BN',
    triple_code: 'BRN',
    numeric_code: '96',
    code_link: 'ISO 3166-2:BN',
    domain: '.bn',
  },
  {
    name: 'Bulgaria',
    official_name: 'the Republic of Bulgaria',
    sovereignty: 'UN member',
    code: 'BG',
    triple_code: 'BGR',
    numeric_code: '100',
    code_link: 'ISO 3166-2:BG',
    domain: '.bg',
  },
  {
    name: 'Burkina Faso',
    official_name: 'Burkina Faso[c]',
    sovereignty: 'UN member',
    code: 'BF',
    triple_code: 'BFA',
    numeric_code: '854',
    code_link: 'ISO 3166-2:BF',
    domain: '.bf',
  },
  {
    name: 'Burma – See Myanmar.',
    official_name: '',
    sovereignty: '',
    code: '',
    triple_code: '',
    numeric_code: "''",
    code_link: '',
    domain: '',
  },
  {
    name: 'Burundi',
    official_name: 'the Republic of Burundi',
    sovereignty: 'UN member',
    code: 'BI',
    triple_code: 'BDI',
    numeric_code: '108',
    code_link: 'ISO 3166-2:BI',
    domain: '.bi',
  },
  {
    name: 'Cabo Verde[j]',
    official_name: 'the Republic of Cabo Verde',
    sovereignty: 'UN member',
    code: 'CV',
    triple_code: 'CPV',
    numeric_code: '132',
    code_link: 'ISO 3166-2:CV',
    domain: '.cv',
  },
  {
    name: 'Cambodia',
    official_name: 'the Kingdom of Cambodia',
    sovereignty: 'UN member',
    code: 'KH',
    triple_code: 'KHM',
    numeric_code: '116',
    code_link: 'ISO 3166-2:KH',
    domain: '.kh',
  },
  {
    name: 'Cameroon',
    official_name: 'the Republic of Cameroon',
    sovereignty: 'UN member',
    code: 'CM',
    triple_code: 'CMR',
    numeric_code: '120',
    code_link: 'ISO 3166-2:CM',
    domain: '.cm',
  },
  {
    name: 'Canada',
    official_name: 'Canada[c]',
    sovereignty: 'UN member',
    code: 'CA',
    triple_code: 'CAN',
    numeric_code: '124',
    code_link: 'ISO 3166-2:CA',
    domain: '.ca',
  },
  {
    name: 'Cape Verde – See Cabo Verde.',
    official_name: '',
    sovereignty: '',
    code: '',
    triple_code: '',
    numeric_code: "''",
    code_link: '',
    domain: '',
  },
  {
    name: 'Caribbean Netherlands – See Bonaire, Sint Eustatius and Saba.',
    official_name: '',
    sovereignty: '',
    code: '',
    triple_code: '',
    numeric_code: "''",
    code_link: '',
    domain: '',
  },
  {
    name: 'Cayman Islands (the)',
    official_name: 'the Cayman Islands[c]',
    sovereignty: 'United Kingdom',
    code: 'KY',
    triple_code: 'CYM',
    numeric_code: '136',
    code_link: 'ISO 3166-2:KY',
    domain: '.ky',
  },
  {
    name: 'Central African Republic (the)',
    official_name: 'the Central African Republic',
    sovereignty: 'UN member',
    code: 'CF',
    triple_code: 'CAF',
    numeric_code: '140',
    code_link: 'ISO 3166-2:CF',
    domain: '.cf',
  },
  {
    name: 'Chad',
    official_name: 'the Republic of Chad',
    sovereignty: 'UN member',
    code: 'TD',
    triple_code: 'TCD',
    numeric_code: '148',
    code_link: 'ISO 3166-2:TD',
    domain: '.td',
  },
  {
    name: 'Chile',
    official_name: 'the Republic of Chile',
    sovereignty: 'UN member',
    code: 'CL',
    triple_code: 'CHL',
    numeric_code: '152',
    code_link: 'ISO 3166-2:CL',
    domain: '.cl',
  },
  {
    name: 'China',
    official_name: "the People's Republic of China",
    sovereignty: 'UN member',
    code: 'CN',
    triple_code: 'CHN',
    numeric_code: '156',
    code_link: 'ISO 3166-2:CN',
    domain: '.cn',
  },
  {
    name: 'China, The Republic of – See Taiwan (Province of China).',
    official_name: '',
    sovereignty: '',
    code: '',
    triple_code: '',
    numeric_code: "''",
    code_link: '',
    domain: '',
  },
  // {
  //   name: 'Christmas Island',
  //   official_name: 'the Territory of Christmas Island[c]',
  //   sovereignty: 'Australia',
  //   code: 'CX',
  //   triple_code: 'CXR',
  //   numeric_code: '162',
  //   code_link: 'ISO 3166-2:CX',
  //   domain: '.cx',
  // },
  // {
  //   name: 'Cocos (Keeling) Islands (the)',
  //   official_name: 'the Territory of Cocos (Keeling) Islands[c]',
  //   sovereignty: 'Australia',
  //   code: 'CC',
  //   triple_code: 'CCK',
  //   numeric_code: '166',
  //   code_link: 'ISO 3166-2:CC',
  //   domain: '.cc',
  // },
  {
    name: 'Colombia',
    official_name: 'the Republic of Colombia',
    sovereignty: 'UN member',
    code: 'CO',
    triple_code: 'COL',
    numeric_code: '170',
    code_link: 'ISO 3166-2:CO',
    domain: '.co',
  },
  {
    name: 'Comoros (the)',
    official_name: 'the Union of the Comoros',
    sovereignty: 'UN member',
    code: 'KM',
    triple_code: 'COM',
    numeric_code: '174',
    code_link: 'ISO 3166-2:KM',
    domain: '.km',
  },
  {
    name: 'Congo (the Democratic Republic of the)',
    official_name: 'the Democratic Republic of the Congo',
    sovereignty: 'UN member',
    code: 'CD',
    triple_code: 'COD',
    numeric_code: '180',
    code_link: 'ISO 3166-2:CD',
    domain: '.cd',
  },
  {
    name: 'Congo (the)[k]',
    official_name: 'the Republic of the Congo',
    sovereignty: 'UN member',
    code: 'CG',
    triple_code: 'COG',
    numeric_code: '178',
    code_link: 'ISO 3166-2:CG',
    domain: '.cg',
  },
  // {
  //   name: 'Cook Islands (the)',
  //   official_name: 'the Cook Islands[c]',
  //   sovereignty: 'New Zealand',
  //   code: 'CK',
  //   triple_code: 'COK',
  //   numeric_code: '184',
  //   code_link: 'ISO 3166-2:CK',
  //   domain: '.ck',
  // },
  {
    name: 'Costa Rica',
    official_name: 'the Republic of Costa Rica',
    sovereignty: 'UN member',
    code: 'CR',
    triple_code: 'CRI',
    numeric_code: '188',
    code_link: 'ISO 3166-2:CR',
    domain: '.cr',
  },
  {
    name: "Côte d'Ivoire[l]",
    official_name: "the Republic of Côte d'Ivoire",
    sovereignty: 'UN member',
    code: 'CI',
    triple_code: 'CIV',
    numeric_code: '384',
    code_link: 'ISO 3166-2:CI',
    domain: '.ci',
  },
  {
    name: 'Croatia',
    official_name: 'the Republic of Croatia',
    sovereignty: 'UN member',
    code: 'HR',
    triple_code: 'HRV',
    numeric_code: '191',
    code_link: 'ISO 3166-2:HR',
    domain: '.hr',
  },
  {
    name: 'Cuba',
    official_name: 'the Republic of Cuba',
    sovereignty: 'UN member',
    code: 'CU',
    triple_code: 'CUB',
    numeric_code: '192',
    code_link: 'ISO 3166-2:CU',
    domain: '.cu',
  },
  {
    name: 'Curaçao',
    official_name: 'the Country of Curaçao[c]',
    sovereignty: 'Netherlands',
    code: 'CW',
    triple_code: 'CUW',
    numeric_code: '531',
    code_link: 'ISO 3166-2:CW',
    domain: '.cw',
  },
  {
    name: 'Cyprus',
    official_name: 'the Republic of Cyprus',
    sovereignty: 'UN member',
    code: 'CY',
    triple_code: 'CYP',
    numeric_code: '196',
    code_link: 'ISO 3166-2:CY',
    domain: '.cy',
  },
  {
    name: 'Czechia[m]',
    official_name: 'the Czech Republic',
    sovereignty: 'UN member',
    code: 'CZ',
    triple_code: 'CZE',
    numeric_code: '203',
    code_link: 'ISO 3166-2:CZ',
    domain: '.cz',
  },
  {
    name: "Democratic People's Republic of Korea – See Korea, The Democratic People's \nRepublic of.",
    official_name: '',
    sovereignty: '',
    code: '',
    triple_code: '',
    numeric_code: "''",
    code_link: '',
    domain: '',
  },
  {
    name: 'Democratic Republic of the Congo – See Congo, The Democratic Republic of the.',
    official_name: '',
    sovereignty: '',
    code: '',
    triple_code: '',
    numeric_code: "''",
    code_link: '',
    domain: '',
  },
  {
    name: 'Denmark',
    official_name: 'the Kingdom of Denmark',
    sovereignty: 'UN member',
    code: 'DK',
    triple_code: 'DNK',
    numeric_code: '208',
    code_link: 'ISO 3166-2:DK',
    domain: '.dk',
  },
  {
    name: 'Djibouti',
    official_name: 'the Republic of Djibouti',
    sovereignty: 'UN member',
    code: 'DJ',
    triple_code: 'DJI',
    numeric_code: '262',
    code_link: 'ISO 3166-2:DJ',
    domain: '.dj',
  },
  {
    name: 'Dominica',
    official_name: 'the Commonwealth of Dominica',
    sovereignty: 'UN member',
    code: 'DM',
    triple_code: 'DMA',
    numeric_code: '212',
    code_link: 'ISO 3166-2:DM',
    domain: '.dm',
  },
  {
    name: 'Dominican Republic (the)',
    official_name: 'the Dominican Republic',
    sovereignty: 'UN member',
    code: 'DO',
    triple_code: 'DOM',
    numeric_code: '214',
    code_link: 'ISO 3166-2:DO',
    domain: '.do',
  },
  {
    name: 'East Timor – See Timor-Leste.',
    official_name: '',
    sovereignty: '',
    code: '',
    triple_code: '',
    numeric_code: "''",
    code_link: '',
    domain: '',
  },
  {
    name: 'Ecuador',
    official_name: 'the Republic of Ecuador',
    sovereignty: 'UN member',
    code: 'EC',
    triple_code: 'ECU',
    numeric_code: '218',
    code_link: 'ISO 3166-2:EC',
    domain: '.ec',
  },
  {
    name: 'Egypt',
    official_name: 'the Arab Republic of Egypt',
    sovereignty: 'UN member',
    code: 'EG',
    triple_code: 'EGY',
    numeric_code: '818',
    code_link: 'ISO 3166-2:EG',
    domain: '.eg',
  },
  {
    name: 'El Salvador',
    official_name: 'the Republic of El Salvador',
    sovereignty: 'UN member',
    code: 'SV',
    triple_code: 'SLV',
    numeric_code: '222',
    code_link: 'ISO 3166-2:SV',
    domain: '.sv',
  },
  {
    name: 'Equatorial Guinea',
    official_name: 'the Republic of Equatorial Guinea',
    sovereignty: 'UN member',
    code: 'GQ',
    triple_code: 'GNQ',
    numeric_code: '226',
    code_link: 'ISO 3166-2:GQ',
    domain: '.gq',
  },
  {
    name: 'Eritrea',
    official_name: 'the State of Eritrea',
    sovereignty: 'UN member',
    code: 'ER',
    triple_code: 'ERI',
    numeric_code: '232',
    code_link: 'ISO 3166-2:ER',
    domain: '.er',
  },
  {
    name: 'Estonia',
    official_name: 'the Republic of Estonia',
    sovereignty: 'UN member',
    code: 'EE',
    triple_code: 'EST',
    numeric_code: '233',
    code_link: 'ISO 3166-2:EE',
    domain: '.ee',
  },
  {
    name: 'Eswatini[n]',
    official_name: 'the Kingdom of Eswatini',
    sovereignty: 'UN member',
    code: 'SZ',
    triple_code: 'SWZ',
    numeric_code: '748',
    code_link: 'ISO 3166-2:SZ',
    domain: '.sz',
  },
  {
    name: 'Ethiopia',
    official_name: 'the Federal Democratic Republic of Ethiopia',
    sovereignty: 'UN member',
    code: 'ET',
    triple_code: 'ETH',
    numeric_code: '231',
    code_link: 'ISO 3166-2:ET',
    domain: '.et',
  },
  {
    name: 'Falkland Islands (the) [Malvinas][o]',
    official_name: 'the Falkland Islands[c][d]',
    sovereignty: 'United Kingdom',
    code: 'FK',
    triple_code: 'FLK',
    numeric_code: '238',
    code_link: 'ISO 3166-2:FK',
    domain: '.fk',
  },
  {
    name: 'Faroe Islands (the)',
    official_name: 'the Faroe Islands[c]',
    sovereignty: 'Denmark',
    code: 'FO',
    triple_code: 'FRO',
    numeric_code: '234',
    code_link: 'ISO 3166-2:FO',
    domain: '.fo',
  },
  {
    name: 'Fiji',
    official_name: 'the Republic of Fiji',
    sovereignty: 'UN member',
    code: 'FJ',
    triple_code: 'FJI',
    numeric_code: '242',
    code_link: 'ISO 3166-2:FJ',
    domain: '.fj',
  },
  {
    name: 'Finland',
    official_name: 'the Republic of Finland',
    sovereignty: 'UN member',
    code: 'FI',
    triple_code: 'FIN',
    numeric_code: '246',
    code_link: 'ISO 3166-2:FI',
    domain: '.fi',
  },
  {
    name: 'France[p]',
    official_name: 'the French Republic',
    sovereignty: 'UN member',
    code: 'FR',
    triple_code: 'FRA',
    numeric_code: '250',
    code_link: 'ISO 3166-2:FR',
    domain: '.fr',
  },
  {
    name: 'French Guiana',
    official_name: 'Guyane[c][d]',
    sovereignty: 'France',
    code: 'GF',
    triple_code: 'GUF',
    numeric_code: '254',
    code_link: 'ISO 3166-2:GF',
    domain: '.gf',
  },
  {
    name: 'French Polynesia',
    official_name: 'Overseas Lands of French Polynesia[c][d]',
    sovereignty: 'France',
    code: 'PF',
    triple_code: 'PYF',
    numeric_code: '258',
    code_link: 'ISO 3166-2:PF',
    domain: '.pf',
  },
  // {
  //   name: 'French Southern Territories (the)[q]',
  //   official_name: 'the French Southern and Antarctic Lands[c]',
  //   sovereignty: 'France',
  //   code: 'TF',
  //   triple_code: 'ATF',
  //   numeric_code: '260',
  //   code_link: 'ISO 3166-2:TF',
  //   domain: '.tf',
  // },
  {
    name: 'Gabon',
    official_name: 'the Gabonese Republic',
    sovereignty: 'UN member',
    code: 'GA',
    triple_code: 'GAB',
    numeric_code: '266',
    code_link: 'ISO 3166-2:GA',
    domain: '.ga',
  },
  {
    name: 'Gambia (the)',
    official_name: 'the Republic of The Gambia',
    sovereignty: 'UN member',
    code: 'GM',
    triple_code: 'GMB',
    numeric_code: '270',
    code_link: 'ISO 3166-2:GM',
    domain: '.gm',
  },
  {
    name: 'Georgia',
    official_name: 'Georgia[c]',
    sovereignty: 'UN member',
    code: 'GE',
    triple_code: 'GEO',
    numeric_code: '268',
    code_link: 'ISO 3166-2:GE',
    domain: '.ge',
  },
  {
    name: 'Germany',
    official_name: 'the Federal Republic of Germany',
    sovereignty: 'UN member',
    code: 'DE',
    triple_code: 'DEU',
    numeric_code: '276',
    code_link: 'ISO 3166-2:DE',
    domain: '.de',
  },
  {
    name: 'Ghana',
    official_name: 'the Republic of Ghana',
    sovereignty: 'UN member',
    code: 'GH',
    triple_code: 'GHA',
    numeric_code: '288',
    code_link: 'ISO 3166-2:GH',
    domain: '.gh',
  },
  // {
  //   name: 'Gibraltar',
  //   official_name: 'Gibraltar[c]',
  //   sovereignty: 'United Kingdom',
  //   code: 'GI',
  //   triple_code: 'GIB',
  //   numeric_code: '292',
  //   code_link: 'ISO 3166-2:GI',
  //   domain: '.gi',
  // },
  {
    name: 'Great Britain – See United Kingdom, The.',
    official_name: '',
    sovereignty: '',
    code: '',
    triple_code: '',
    numeric_code: "''",
    code_link: '',
    domain: '',
  },
  {
    name: 'Greece',
    official_name: 'the Hellenic Republic',
    sovereignty: 'UN member',
    code: 'GR',
    triple_code: 'GRC',
    numeric_code: '300',
    code_link: 'ISO 3166-2:GR',
    domain: '.gr',
  },
  {
    name: 'Greenland',
    official_name: 'Greenland[c]',
    sovereignty: 'Denmark',
    code: 'GL',
    triple_code: 'GRL',
    numeric_code: '304',
    code_link: 'ISO 3166-2:GL',
    domain: '.gl',
  },
  {
    name: 'Grenada',
    official_name: 'Grenada[c]',
    sovereignty: 'UN member',
    code: 'GD',
    triple_code: 'GRD',
    numeric_code: '308',
    code_link: 'ISO 3166-2:GD',
    domain: '.gd',
  },
  {
    name: 'Guadeloupe',
    official_name: 'Guadeloupe[c][d]',
    sovereignty: 'France',
    code: 'GP',
    triple_code: 'GLP',
    numeric_code: '312',
    code_link: 'ISO 3166-2:GP',
    domain: '.gp',
  },
  // {
  //   name: 'Guam',
  //   official_name: 'Guam[c]',
  //   sovereignty: 'United States',
  //   code: 'GU',
  //   triple_code: 'GUM',
  //   numeric_code: '316',
  //   code_link: 'ISO 3166-2:GU',
  //   domain: '.gu',
  // },
  {
    name: 'Guatemala',
    official_name: 'the Republic of Guatemala',
    sovereignty: 'UN member',
    code: 'GT',
    triple_code: 'GTM',
    numeric_code: '320',
    code_link: 'ISO 3166-2:GT',
    domain: '.gt',
  },
  // {
  //   name: 'Guernsey',
  //   official_name: 'the Bailiwick of Guernsey[c]',
  //   sovereignty: 'British Crown',
  //   code: 'GG',
  //   triple_code: 'GGY',
  //   numeric_code: '831',
  //   code_link: 'ISO 3166-2:GG',
  //   domain: '.gg',
  // },
  {
    name: 'Guinea',
    official_name: 'the Republic of Guinea',
    sovereignty: 'UN member',
    code: 'GN',
    triple_code: 'GIN',
    numeric_code: '324',
    code_link: 'ISO 3166-2:GN',
    domain: '.gn',
  },
  {
    name: 'Guinea-Bissau',
    official_name: 'the Republic of Guinea-Bissau',
    sovereignty: 'UN member',
    code: 'GW',
    triple_code: 'GNB',
    numeric_code: '624',
    code_link: 'ISO 3166-2:GW',
    domain: '.gw',
  },
  {
    name: 'Guyana',
    official_name: 'the Co-operative Republic of Guyana',
    sovereignty: 'UN member',
    code: 'GY',
    triple_code: 'GUY',
    numeric_code: '328',
    code_link: 'ISO 3166-2:GY',
    domain: '.gy',
  },
  {
    name: 'Haiti',
    official_name: 'the Republic of Haiti',
    sovereignty: 'UN member',
    code: 'HT',
    triple_code: 'HTI',
    numeric_code: '332',
    code_link: 'ISO 3166-2:HT',
    domain: '.ht',
  },
  // {
  //   name: 'Heard Island and McDonald Islands',
  //   official_name: 'the Territory of Heard Island and McDonald Islands[c]',
  //   sovereignty: 'Australia',
  //   code: 'HM',
  //   triple_code: 'HMD',
  //   numeric_code: '334',
  //   code_link: 'ISO 3166-2:HM',
  //   domain: '.hm',
  // },
  {
    name: 'Holy See (the)[r]',
    official_name: 'the Holy See[c]',
    sovereignty: 'UN observer',
    code: 'VA',
    triple_code: 'VAT',
    numeric_code: '336',
    code_link: 'ISO 3166-2:VA',
    domain: '.va',
  },
  {
    name: 'Honduras',
    official_name: 'the Republic of Honduras',
    sovereignty: 'UN member',
    code: 'HN',
    triple_code: 'HND',
    numeric_code: '340',
    code_link: 'ISO 3166-2:HN',
    domain: '.hn',
  },
  {
    name: 'Hong Kong',
    official_name: 'the Hong Kong Special Administrative Region of China[10]',
    sovereignty: 'China',
    code: 'HK',
    triple_code: 'HKG',
    numeric_code: '344',
    code_link: 'ISO 3166-2:HK',
    domain: '.hk',
  },
  {
    name: 'Hungary',
    official_name: 'Hungary[c]',
    sovereignty: 'UN member',
    code: 'HU',
    triple_code: 'HUN',
    numeric_code: '348',
    code_link: 'ISO 3166-2:HU',
    domain: '.hu',
  },
  {
    name: 'Iceland',
    official_name: 'Iceland[c]',
    sovereignty: 'UN member',
    code: 'IS',
    triple_code: 'ISL',
    numeric_code: '352',
    code_link: 'ISO 3166-2:IS',
    domain: '.is',
  },
  {
    name: 'India',
    official_name: 'the Republic of India',
    sovereignty: 'UN member',
    code: 'IN',
    triple_code: 'IND',
    numeric_code: '356',
    code_link: 'ISO 3166-2:IN',
    domain: '.in',
  },
  {
    name: 'Indonesia',
    official_name: 'the Republic of Indonesia',
    sovereignty: 'UN member',
    code: 'ID',
    triple_code: 'IDN',
    numeric_code: '360',
    code_link: 'ISO 3166-2:ID',
    domain: '.id',
  },
  {
    name: 'Iran (Islamic Republic of)[s]',
    official_name: 'the Islamic Republic of Iran',
    sovereignty: 'UN member',
    code: 'IR',
    triple_code: 'IRN',
    numeric_code: '364',
    code_link: 'ISO 3166-2:IR',
    domain: '.ir',
  },
  {
    name: 'Iraq',
    official_name: 'the Republic of Iraq',
    sovereignty: 'UN member',
    code: 'IQ',
    triple_code: 'IRQ',
    numeric_code: '368',
    code_link: 'ISO 3166-2:IQ',
    domain: '.iq',
  },
  {
    name: 'Ireland',
    official_name: 'Ireland[c]',
    sovereignty: 'UN member',
    code: 'IE',
    triple_code: 'IRL',
    numeric_code: '372',
    code_link: 'ISO 3166-2:IE',
    domain: '.ie',
  },
  // {
  //   name: 'Isle of Man',
  //   official_name: 'the Isle of Man[c]',
  //   sovereignty: 'British Crown',
  //   code: 'IM',
  //   triple_code: 'IMN',
  //   numeric_code: '833',
  //   code_link: 'ISO 3166-2:IM',
  //   domain: '.im',
  // },
  {
    name: 'Israel',
    official_name: 'the State of Israel',
    sovereignty: 'UN member',
    code: 'IL',
    triple_code: 'ISR',
    numeric_code: '376',
    code_link: 'ISO 3166-2:IL',
    domain: '.il',
  },
  {
    name: 'Italy',
    official_name: 'the Italian Republic',
    sovereignty: 'UN member',
    code: 'IT',
    triple_code: 'ITA',
    numeric_code: '380',
    code_link: 'ISO 3166-2:IT',
    domain: '.it',
  },
  {
    name: "Ivory Coast – See Côte d'Ivoire.",
    official_name: '',
    sovereignty: '',
    code: '',
    triple_code: '',
    numeric_code: "''",
    code_link: '',
    domain: '',
  },
  {
    name: 'Jamaica',
    official_name: 'Jamaica[c]',
    sovereignty: 'UN member',
    code: 'JM',
    triple_code: 'JAM',
    numeric_code: '388',
    code_link: 'ISO 3166-2:JM',
    domain: '.jm',
  },
  {
    name: 'Jan Mayen – See Svalbard and Jan Mayen.',
    official_name: '',
    sovereignty: '',
    code: '',
    triple_code: '',
    numeric_code: "''",
    code_link: '',
    domain: '',
  },
  {
    name: 'Japan',
    official_name: 'Japan[c]',
    sovereignty: 'UN member',
    code: 'JP',
    triple_code: 'JPN',
    numeric_code: '392',
    code_link: 'ISO 3166-2:JP',
    domain: '.jp',
  },
  // {
  //   name: 'Jersey',
  //   official_name: 'the Bailiwick of Jersey[c]',
  //   sovereignty: 'British Crown',
  //   code: 'JE',
  //   triple_code: 'JEY',
  //   numeric_code: '832',
  //   code_link: 'ISO 3166-2:JE',
  //   domain: '.je',
  // },
  {
    name: 'Jordan',
    official_name: 'the Hashemite Kingdom of Jordan',
    sovereignty: 'UN member',
    code: 'JO',
    triple_code: 'JOR',
    numeric_code: '400',
    code_link: 'ISO 3166-2:JO',
    domain: '.jo',
  },
  {
    name: 'Kazakhstan',
    official_name: 'the Republic of Kazakhstan',
    sovereignty: 'UN member',
    code: 'KZ',
    triple_code: 'KAZ',
    numeric_code: '398',
    code_link: 'ISO 3166-2:KZ',
    domain: '.kz',
  },
  {
    name: 'Kenya',
    official_name: 'the Republic of Kenya',
    sovereignty: 'UN member',
    code: 'KE',
    triple_code: 'KEN',
    numeric_code: '404',
    code_link: 'ISO 3166-2:KE',
    domain: '.ke',
  },
  // {
  //   name: 'Kiribati',
  //   official_name: 'the Republic of Kiribati',
  //   sovereignty: 'UN member',
  //   code: 'KI',
  //   triple_code: 'KIR',
  //   numeric_code: '296',
  //   code_link: 'ISO 3166-2:KI',
  //   domain: '.ki',
  // },
  {
    name: "Korea (the Democratic People's Republic of)[t]",
    official_name: "the Democratic People's Republic of Korea",
    sovereignty: 'UN member',
    code: 'KP',
    triple_code: 'PRK',
    numeric_code: '408',
    code_link: 'ISO 3166-2:KP',
    domain: '.kp',
  },
  {
    name: 'Korea (the Republic of)[u]',
    official_name: 'the Republic of Korea',
    sovereignty: 'UN member',
    code: 'KR',
    triple_code: 'KOR',
    numeric_code: '410',
    code_link: 'ISO 3166-2:KR',
    domain: '.kr',
  },
  {
    name: 'Kuwait',
    official_name: 'the State of Kuwait',
    sovereignty: 'UN member',
    code: 'KW',
    triple_code: 'KWT',
    numeric_code: '414',
    code_link: 'ISO 3166-2:KW',
    domain: '.kw',
  },
  {
    name: 'Kyrgyzstan',
    official_name: 'the Kyrgyz Republic',
    sovereignty: 'UN member',
    code: 'KG',
    triple_code: 'KGZ',
    numeric_code: '417',
    code_link: 'ISO 3166-2:KG',
    domain: '.kg',
  },
  {
    name: "Lao People's Democratic Republic (the)[v]",
    official_name: "the Lao People's Democratic Republic",
    sovereignty: 'UN member',
    code: 'LA',
    triple_code: 'LAO',
    numeric_code: '418',
    code_link: 'ISO 3166-2:LA',
    domain: '.la',
  },
  {
    name: 'Latvia',
    official_name: 'the Republic of Latvia',
    sovereignty: 'UN member',
    code: 'LV',
    triple_code: 'LVA',
    numeric_code: '428',
    code_link: 'ISO 3166-2:LV',
    domain: '.lv',
  },
  {
    name: 'Lebanon',
    official_name: 'the Lebanese Republic',
    sovereignty: 'UN member',
    code: 'LB',
    triple_code: 'LBN',
    numeric_code: '422',
    code_link: 'ISO 3166-2:LB',
    domain: '.lb',
  },
  {
    name: 'Lesotho',
    official_name: 'the Kingdom of Lesotho',
    sovereignty: 'UN member',
    code: 'LS',
    triple_code: 'LSO',
    numeric_code: '426',
    code_link: 'ISO 3166-2:LS',
    domain: '.ls',
  },
  {
    name: 'Liberia',
    official_name: 'the Republic of Liberia',
    sovereignty: 'UN member',
    code: 'LR',
    triple_code: 'LBR',
    numeric_code: '430',
    code_link: 'ISO 3166-2:LR',
    domain: '.lr',
  },
  {
    name: 'Libya',
    official_name: 'the State of Libya',
    sovereignty: 'UN member',
    code: 'LY',
    triple_code: 'LBY',
    numeric_code: '434',
    code_link: 'ISO 3166-2:LY',
    domain: '.ly',
  },
  {
    name: 'Liechtenstein',
    official_name: 'the Principality of Liechtenstein',
    sovereignty: 'UN member',
    code: 'LI',
    triple_code: 'LIE',
    numeric_code: '438',
    code_link: 'ISO 3166-2:LI',
    domain: '.li',
  },
  {
    name: 'Lithuania',
    official_name: 'the Republic of Lithuania',
    sovereignty: 'UN member',
    code: 'LT',
    triple_code: 'LTU',
    numeric_code: '440',
    code_link: 'ISO 3166-2:LT',
    domain: '.lt',
  },
  {
    name: 'Luxembourg',
    official_name: 'the Grand Duchy of Luxembourg',
    sovereignty: 'UN member',
    code: 'LU',
    triple_code: 'LUX',
    numeric_code: '442',
    code_link: 'ISO 3166-2:LU',
    domain: '.lu',
  },
  // {
  //   name: 'Macao[w]',
  //   official_name: 'the Macao Special Administrative Region of China[11]',
  //   sovereignty: 'China',
  //   code: 'MO',
  //   triple_code: 'MAC',
  //   numeric_code: '446',
  //   code_link: 'ISO 3166-2:MO',
  //   domain: '.mo',
  // },
  {
    name: 'Madagascar',
    official_name: 'the Republic of Madagascar',
    sovereignty: 'UN member',
    code: 'MG',
    triple_code: 'MDG',
    numeric_code: '450',
    code_link: 'ISO 3166-2:MG',
    domain: '.mg',
  },
  {
    name: 'Malawi',
    official_name: 'the Republic of Malawi',
    sovereignty: 'UN member',
    code: 'MW',
    triple_code: 'MWI',
    numeric_code: '454',
    code_link: 'ISO 3166-2:MW',
    domain: '.mw',
  },
  {
    name: 'Malaysia',
    official_name: 'Malaysia[c]',
    sovereignty: 'UN member',
    code: 'MY',
    triple_code: 'MYS',
    numeric_code: '458',
    code_link: 'ISO 3166-2:MY',
    domain: '.my',
  },
  {
    name: 'Maldives',
    official_name: 'the Republic of Maldives',
    sovereignty: 'UN member',
    code: 'MV',
    triple_code: 'MDV',
    numeric_code: '462',
    code_link: 'ISO 3166-2:MV',
    domain: '.mv',
  },
  {
    name: 'Mali',
    official_name: 'the Republic of Mali',
    sovereignty: 'UN member',
    code: 'ML',
    triple_code: 'MLI',
    numeric_code: '466',
    code_link: 'ISO 3166-2:ML',
    domain: '.ml',
  },
  {
    name: 'Malta',
    official_name: 'the Republic of Malta',
    sovereignty: 'UN member',
    code: 'MT',
    triple_code: 'MLT',
    numeric_code: '470',
    code_link: 'ISO 3166-2:MT',
    domain: '.mt',
  },
  // {
  //   name: 'Marshall Islands (the)',
  //   official_name: 'the Republic of the Marshall Islands',
  //   sovereignty: 'UN member',
  //   code: 'MH',
  //   triple_code: 'MHL',
  //   numeric_code: '584',
  //   code_link: 'ISO 3166-2:MH',
  //   domain: '.mh',
  // },
  {
    name: 'Martinique',
    official_name: 'Martinique[c][d]',
    sovereignty: 'France',
    code: 'MQ',
    triple_code: 'MTQ',
    numeric_code: '474',
    code_link: 'ISO 3166-2:MQ',
    domain: '.mq',
  },
  {
    name: 'Mauritania',
    official_name: 'the Islamic Republic of Mauritania',
    sovereignty: 'UN member',
    code: 'MR',
    triple_code: 'MRT',
    numeric_code: '478',
    code_link: 'ISO 3166-2:MR',
    domain: '.mr',
  },
  {
    name: 'Mauritius',
    official_name: 'the Republic of Mauritius',
    sovereignty: 'UN member',
    code: 'MU',
    triple_code: 'MUS',
    numeric_code: '480',
    code_link: 'ISO 3166-2:MU',
    domain: '.mu',
  },
  {
    name: 'Mayotte',
    official_name: 'the Department of Mayotte[c][d]',
    sovereignty: 'France',
    code: 'YT',
    triple_code: 'MYT',
    numeric_code: '175',
    code_link: 'ISO 3166-2:YT',
    domain: '.yt',
  },
  {
    name: 'Mexico',
    official_name: 'the United Mexican States',
    sovereignty: 'UN member',
    code: 'MX',
    triple_code: 'MEX',
    numeric_code: '484',
    code_link: 'ISO 3166-2:MX',
    domain: '.mx',
  },
  // {
  //   name: 'Micronesia (Federated States of)',
  //   official_name: 'the Federated States of Micronesia',
  //   sovereignty: 'UN member',
  //   code: 'FM',
  //   triple_code: 'FSM',
  //   numeric_code: '583',
  //   code_link: 'ISO 3166-2:FM',
  //   domain: '.fm',
  // },
  {
    name: 'Moldova (the Republic of)',
    official_name: 'the Republic of Moldova',
    sovereignty: 'UN member',
    code: 'MD',
    triple_code: 'MDA',
    numeric_code: '498',
    code_link: 'ISO 3166-2:MD',
    domain: '.md',
  },
  {
    name: 'Monaco',
    official_name: 'the Principality of Monaco',
    sovereignty: 'UN member',
    code: 'MC',
    triple_code: 'MCO',
    numeric_code: '492',
    code_link: 'ISO 3166-2:MC',
    domain: '.mc',
  },
  {
    name: 'Mongolia',
    official_name: 'Mongolia[c]',
    sovereignty: 'UN member',
    code: 'MN',
    triple_code: 'MNG',
    numeric_code: '496',
    code_link: 'ISO 3166-2:MN',
    domain: '.mn',
  },
  {
    name: 'Montenegro',
    official_name: 'Montenegro[c]',
    sovereignty: 'UN member',
    code: 'ME',
    triple_code: 'MNE',
    numeric_code: '499',
    code_link: 'ISO 3166-2:ME',
    domain: '.me',
  },
  {
    name: 'Montserrat',
    official_name: 'Montserrat[c]',
    sovereignty: 'United Kingdom',
    code: 'MS',
    triple_code: 'MSR',
    numeric_code: '500',
    code_link: 'ISO 3166-2:MS',
    domain: '.ms',
  },
  {
    name: 'Morocco',
    official_name: 'the Kingdom of Morocco',
    sovereignty: 'UN member',
    code: 'MA',
    triple_code: 'MAR',
    numeric_code: '504',
    code_link: 'ISO 3166-2:MA',
    domain: '.ma',
  },
  {
    name: 'Mozambique',
    official_name: 'the Republic of Mozambique',
    sovereignty: 'UN member',
    code: 'MZ',
    triple_code: 'MOZ',
    numeric_code: '508',
    code_link: 'ISO 3166-2:MZ',
    domain: '.mz',
  },
  {
    name: 'Myanmar[x]',
    official_name: 'the Republic of the Union of Myanmar[d]',
    sovereignty: 'UN member',
    code: 'MM',
    triple_code: 'MMR',
    numeric_code: '104',
    code_link: 'ISO 3166-2:MM',
    domain: '.mm',
  },
  {
    name: 'Namibia',
    official_name: 'the Republic of Namibia',
    sovereignty: 'UN member',
    code: 'NA',
    triple_code: 'NAM',
    numeric_code: '516',
    code_link: 'ISO 3166-2:NA',
    domain: '.na',
  },
  {
    name: 'Nauru',
    official_name: 'the Republic of Nauru',
    sovereignty: 'UN member',
    code: 'NR',
    triple_code: 'NRU',
    numeric_code: '520',
    code_link: 'ISO 3166-2:NR',
    domain: '.nr',
  },
  {
    name: 'Nepal',
    official_name: 'the Federal Democratic Republic of Nepal[c][d]',
    sovereignty: 'UN member',
    code: 'NP',
    triple_code: 'NPL',
    numeric_code: '524',
    code_link: 'ISO 3166-2:NP',
    domain: '.np',
  },
  {
    name: 'Netherlands (Kingdom of the)',
    official_name: 'the Kingdom of the Netherlands',
    sovereignty: 'UN member',
    code: 'NL',
    triple_code: 'NLD',
    numeric_code: '528',
    code_link: 'ISO 3166-2:NL',
    domain: '.nl',
  },
  {
    name: 'New Caledonia',
    official_name: 'New Caledonia[c]',
    sovereignty: 'France',
    code: 'NC',
    triple_code: 'NCL',
    numeric_code: '540',
    code_link: 'ISO 3166-2:NC',
    domain: '.nc',
  },
  {
    name: 'New Zealand',
    official_name: 'New Zealand[c]',
    sovereignty: 'UN member',
    code: 'NZ',
    triple_code: 'NZL',
    numeric_code: '554',
    code_link: 'ISO 3166-2:NZ',
    domain: '.nz',
  },
  {
    name: 'Nicaragua',
    official_name: 'the Republic of Nicaragua',
    sovereignty: 'UN member',
    code: 'NI',
    triple_code: 'NIC',
    numeric_code: '558',
    code_link: 'ISO 3166-2:NI',
    domain: '.ni',
  },
  {
    name: 'Niger (the)',
    official_name: 'the Republic of the Niger',
    sovereignty: 'UN member',
    code: 'NE',
    triple_code: 'NER',
    numeric_code: '562',
    code_link: 'ISO 3166-2:NE',
    domain: '.ne',
  },
  {
    name: 'Nigeria',
    official_name: 'the Federal Republic of Nigeria',
    sovereignty: 'UN member',
    code: 'NG',
    triple_code: 'NGA',
    numeric_code: '566',
    code_link: 'ISO 3166-2:NG',
    domain: '.ng',
  },
  // {
  //   name: 'Niue',
  //   official_name: 'Niue[c]',
  //   sovereignty: 'New Zealand',
  //   code: 'NU',
  //   triple_code: 'NIU',
  //   numeric_code: '570',
  //   code_link: 'ISO 3166-2:NU',
  //   domain: '.nu',
  // },
  // {
  //   name: 'Norfolk Island',
  //   official_name: 'the Territory of Norfolk Island[c]',
  //   sovereignty: 'Australia',
  //   code: 'NF',
  //   triple_code: 'NFK',
  //   numeric_code: '574',
  //   code_link: 'ISO 3166-2:NF',
  //   domain: '.nf',
  // },
  {
    name: "North Korea – See Korea, The Democratic People's Republic of.",
    official_name: '',
    sovereignty: '',
    code: '',
    triple_code: '',
    numeric_code: "''",
    code_link: '',
    domain: '',
  },
  {
    name: 'North Macedonia[y]',
    official_name: 'the Republic of North Macedonia[12]',
    sovereignty: 'UN member',
    code: 'MK',
    triple_code: 'MKD',
    numeric_code: '807',
    code_link: 'ISO 3166-2:MK',
    domain: '.mk',
  },
  // {
  //   name: 'Northern Mariana Islands (the)',
  //   official_name: 'the Commonwealth of the Northern Mariana Islands',
  //   sovereignty: 'United States',
  //   code: 'MP',
  //   triple_code: 'MNP',
  //   numeric_code: '580',
  //   code_link: 'ISO 3166-2:MP',
  //   domain: '.mp',
  // },
  {
    name: 'Norway',
    official_name: 'the Kingdom of Norway',
    sovereignty: 'UN member',
    code: 'NO',
    triple_code: 'NOR',
    numeric_code: '578',
    code_link: 'ISO 3166-2:NO',
    domain: '.no',
  },
  {
    name: 'Oman',
    official_name: 'the Sultanate of Oman',
    sovereignty: 'UN member',
    code: 'OM',
    triple_code: 'OMN',
    numeric_code: '512',
    code_link: 'ISO 3166-2:OM',
    domain: '.om',
  },
  {
    name: 'Pakistan',
    official_name: 'the Islamic Republic of Pakistan',
    sovereignty: 'UN member',
    code: 'PK',
    triple_code: 'PAK',
    numeric_code: '586',
    code_link: 'ISO 3166-2:PK',
    domain: '.pk',
  },
  // {
  //   name: 'Palau',
  //   official_name: 'the Republic of Palau',
  //   sovereignty: 'UN member',
  //   code: 'PW',
  //   triple_code: 'PLW',
  //   numeric_code: '585',
  //   code_link: 'ISO 3166-2:PW',
  //   domain: '.pw',
  // },
  {
    name: 'Palestine, State of',
    official_name: 'the State of Palestine[d]',
    sovereignty: 'UN observer',
    code: 'PS',
    triple_code: 'PSE',
    numeric_code: '275',
    code_link: 'ISO 3166-2:PS',
    domain: '.ps',
  },
  {
    name: 'Panama',
    official_name: 'the Republic of Panama',
    sovereignty: 'UN member',
    code: 'PA',
    triple_code: 'PAN',
    numeric_code: '591',
    code_link: 'ISO 3166-2:PA',
    domain: '.pa',
  },
  {
    name: 'Papua New Guinea',
    official_name: 'the Independent State of Papua New Guinea',
    sovereignty: 'UN member',
    code: 'PG',
    triple_code: 'PNG',
    numeric_code: '598',
    code_link: 'ISO 3166-2:PG',
    domain: '.pg',
  },
  {
    name: 'Paraguay',
    official_name: 'the Republic of Paraguay',
    sovereignty: 'UN member',
    code: 'PY',
    triple_code: 'PRY',
    numeric_code: '600',
    code_link: 'ISO 3166-2:PY',
    domain: '.py',
  },
  {
    name: "People's Republic of China – See China.",
    official_name: '',
    sovereignty: '',
    code: '',
    triple_code: '',
    numeric_code: "''",
    code_link: '',
    domain: '',
  },
  {
    name: 'Peru',
    official_name: 'the Republic of Peru',
    sovereignty: 'UN member',
    code: 'PE',
    triple_code: 'PER',
    numeric_code: '604',
    code_link: 'ISO 3166-2:PE',
    domain: '.pe',
  },
  {
    name: 'Philippines (the)',
    official_name: 'the Republic of the Philippines',
    sovereignty: 'UN member',
    code: 'PH',
    triple_code: 'PHL',
    numeric_code: '608',
    code_link: 'ISO 3166-2:PH',
    domain: '.ph',
  },
  {
    name: 'Pitcairn[z]',
    official_name: 'the Pitcairn, Henderson, Ducie and Oeno Islands[c]',
    sovereignty: 'United Kingdom',
    code: 'PN',
    triple_code: 'PCN',
    numeric_code: '612',
    code_link: 'ISO 3166-2:PN',
    domain: '.pn',
  },
  {
    name: 'Poland',
    official_name: 'the Republic of Poland',
    sovereignty: 'UN member',
    code: 'PL',
    triple_code: 'POL',
    numeric_code: '616',
    code_link: 'ISO 3166-2:PL',
    domain: '.pl',
  },
  {
    name: 'Portugal',
    official_name: 'the Portuguese Republic',
    sovereignty: 'UN member',
    code: 'PT',
    triple_code: 'PRT',
    numeric_code: '620',
    code_link: 'ISO 3166-2:PT',
    domain: '.pt',
  },
  {
    name: 'Puerto Rico',
    official_name: 'the Commonwealth of Puerto Rico[c]',
    sovereignty: 'United States',
    code: 'PR',
    triple_code: 'PRI',
    numeric_code: '630',
    code_link: 'ISO 3166-2:PR',
    domain: '.pr',
  },
  {
    name: 'Qatar',
    official_name: 'the State of Qatar',
    sovereignty: 'UN member',
    code: 'QA',
    triple_code: 'QAT',
    numeric_code: '634',
    code_link: 'ISO 3166-2:QA',
    domain: '.qa',
  },
  {
    name: 'Republic of China – See Taiwan (Province of China).',
    official_name: '',
    sovereignty: '',
    code: '',
    triple_code: '',
    numeric_code: "''",
    code_link: '',
    domain: '',
  },
  {
    name: 'Republic of Korea – See Korea, The Republic of.',
    official_name: '',
    sovereignty: '',
    code: '',
    triple_code: '',
    numeric_code: "''",
    code_link: '',
    domain: '',
  },
  {
    name: 'Republic of the Congo – See Congo, The.',
    official_name: '',
    sovereignty: '',
    code: '',
    triple_code: '',
    numeric_code: "''",
    code_link: '',
    domain: '',
  },
  {
    name: 'Réunion',
    official_name: 'Réunion[c][d]',
    sovereignty: 'France',
    code: 'RE',
    triple_code: 'REU',
    numeric_code: '638',
    code_link: 'ISO 3166-2:RE',
    domain: '.re',
  },
  {
    name: 'Romania',
    official_name: 'Romania[c]',
    sovereignty: 'UN member',
    code: 'RO',
    triple_code: 'ROU',
    numeric_code: '642',
    code_link: 'ISO 3166-2:RO',
    domain: '.ro',
  },
  {
    name: 'Russian Federation (the)[aa]',
    official_name: 'the Russian Federation',
    sovereignty: 'UN member',
    code: 'RU',
    triple_code: 'RUS',
    numeric_code: '643',
    code_link: 'ISO 3166-2:RU',
    domain: '.ru',
  },
  {
    name: 'Rwanda',
    official_name: 'the Republic of Rwanda',
    sovereignty: 'UN member',
    code: 'RW',
    triple_code: 'RWA',
    numeric_code: '646',
    code_link: 'ISO 3166-2:RW',
    domain: '.rw',
  },
  {
    name: 'Saba – See Bonaire, Sint Eustatius and Saba.',
    official_name: '',
    sovereignty: '',
    code: '',
    triple_code: '',
    numeric_code: "''",
    code_link: '',
    domain: '',
  },
  {
    name: 'Sahrawi Arab Democratic Republic – See Western Sahara.',
    official_name: '',
    sovereignty: '',
    code: '',
    triple_code: '',
    numeric_code: "''",
    code_link: '',
    domain: '',
  },
  // {
  //   name: 'Saint Barthélemy',
  //   official_name: 'the Collectivity of Saint-Barthélemy[c]',
  //   sovereignty: 'France',
  //   code: 'BL',
  //   triple_code: 'BLM',
  //   numeric_code: '652',
  //   code_link: 'ISO 3166-2:BL',
  //   domain: '.bl',
  // },
  // {
  //   name: 'Saint Helena\nAscension Island\nTristan da Cunha',
  //   official_name: 'Saint Helena, Ascension and Tristan da Cunha[c]',
  //   sovereignty: 'United Kingdom',
  //   code: 'SH',
  //   triple_code: 'SHN',
  //   numeric_code: '654',
  //   code_link: 'ISO 3166-2:SH',
  //   domain: '.sh',
  // },
  {
    name: 'Saint Kitts and Nevis',
    official_name: 'the Federation of Saint Kitts and Nevis[c]',
    sovereignty: 'UN member',
    code: 'KN',
    triple_code: 'KNA',
    numeric_code: '659',
    code_link: 'ISO 3166-2:KN',
    domain: '.kn',
  },
  {
    name: 'Saint Lucia',
    official_name: 'Saint Lucia[c]',
    sovereignty: 'UN member',
    code: 'LC',
    triple_code: 'LCA',
    numeric_code: '662',
    code_link: 'ISO 3166-2:LC',
    domain: '.lc',
  },
  // {
  //   name: 'Saint Martin (French part)',
  //   official_name: 'the Collectivity of Saint-Martin[c]',
  //   sovereignty: 'France',
  //   code: 'MF',
  //   triple_code: 'MAF',
  //   numeric_code: '663',
  //   code_link: 'ISO 3166-2:MF',
  //   domain: '.mf',
  // },
  // {
  //   name: 'Saint Pierre and Miquelon',
  //   official_name: 'the Overseas Collectivity of Saint-Pierre and Miquelon[c]',
  //   sovereignty: 'France',
  //   code: 'PM',
  //   triple_code: 'SPM',
  //   numeric_code: '666',
  //   code_link: 'ISO 3166-2:PM',
  //   domain: '.pm',
  // },
  {
    name: 'Saint Vincent and the Grenadines',
    official_name: 'Saint Vincent and the Grenadines[c]',
    sovereignty: 'UN member',
    code: 'VC',
    triple_code: 'VCT',
    numeric_code: '670',
    code_link: 'ISO 3166-2:VC',
    domain: '.vc',
  },
  // {
  //   name: 'Samoa',
  //   official_name: 'the Independent State of Samoa',
  //   sovereignty: 'UN member',
  //   code: 'WS',
  //   triple_code: 'WSM',
  //   numeric_code: '882',
  //   code_link: 'ISO 3166-2:WS',
  //   domain: '.ws',
  // },
  {
    name: 'San Marino',
    official_name: 'the Republic of San Marino',
    sovereignty: 'UN member',
    code: 'SM',
    triple_code: 'SMR',
    numeric_code: '674',
    code_link: 'ISO 3166-2:SM',
    domain: '.sm',
  },
  {
    name: 'Sao Tome and Principe',
    official_name: 'the Democratic Republic of São Tomé and Príncipe',
    sovereignty: 'UN member',
    code: 'ST',
    triple_code: 'STP',
    numeric_code: '678',
    code_link: 'ISO 3166-2:ST',
    domain: '.st',
  },
  {
    name: 'Saudi Arabia',
    official_name: 'the Kingdom of Saudi Arabia',
    sovereignty: 'UN member',
    code: 'SA',
    triple_code: 'SAU',
    numeric_code: '682',
    code_link: 'ISO 3166-2:SA',
    domain: '.sa',
  },
  {
    name: 'Senegal',
    official_name: 'the Republic of Senegal',
    sovereignty: 'UN member',
    code: 'SN',
    triple_code: 'SEN',
    numeric_code: '686',
    code_link: 'ISO 3166-2:SN',
    domain: '.sn',
  },
  {
    name: 'Serbia',
    official_name: 'the Republic of Serbia',
    sovereignty: 'UN member',
    code: 'RS',
    triple_code: 'SRB',
    numeric_code: '688',
    code_link: 'ISO 3166-2:RS',
    domain: '.rs',
  },
  {
    name: 'Seychelles',
    official_name: 'the Republic of Seychelles',
    sovereignty: 'UN member',
    code: 'SC',
    triple_code: 'SYC',
    numeric_code: '690',
    code_link: 'ISO 3166-2:SC',
    domain: '.sc',
  },
  {
    name: 'Sierra Leone',
    official_name: 'the Republic of Sierra Leone',
    sovereignty: 'UN member',
    code: 'SL',
    triple_code: 'SLE',
    numeric_code: '694',
    code_link: 'ISO 3166-2:SL',
    domain: '.sl',
  },
  {
    name: 'Singapore',
    official_name: 'the Republic of Singapore',
    sovereignty: 'UN member',
    code: 'SG',
    triple_code: 'SGP',
    numeric_code: '702',
    code_link: 'ISO 3166-2:SG',
    domain: '.sg',
  },
  {
    name: 'Sint Eustatius – See Bonaire, Sint Eustatius and Saba.',
    official_name: '',
    sovereignty: '',
    code: '',
    triple_code: '',
    numeric_code: "''",
    code_link: '',
    domain: '',
  },
  {
    name: 'Sint Maarten (Dutch part)',
    official_name: 'Sint Maarten[c]',
    sovereignty: 'Netherlands',
    code: 'SX',
    triple_code: 'SXM',
    numeric_code: '534',
    code_link: 'ISO 3166-2:SX',
    domain: '.sx',
  },
  {
    name: 'Slovakia',
    official_name: 'the Slovak Republic',
    sovereignty: 'UN member',
    code: 'SK',
    triple_code: 'SVK',
    numeric_code: '703',
    code_link: 'ISO 3166-2:SK',
    domain: '.sk',
  },
  {
    name: 'Slovenia',
    official_name: 'the Republic of Slovenia',
    sovereignty: 'UN member',
    code: 'SI',
    triple_code: 'SVN',
    numeric_code: '705',
    code_link: 'ISO 3166-2:SI',
    domain: '.si',
  },
  {
    name: 'Solomon Islands',
    official_name: 'the Solomon Islands[c]',
    sovereignty: 'UN member',
    code: 'SB',
    triple_code: 'SLB',
    numeric_code: '90',
    code_link: 'ISO 3166-2:SB',
    domain: '.sb',
  },
  {
    name: 'Somalia',
    official_name: 'the Federal Republic of Somalia',
    sovereignty: 'UN member',
    code: 'SO',
    triple_code: 'SOM',
    numeric_code: '706',
    code_link: 'ISO 3166-2:SO',
    domain: '.so',
  },
  {
    name: 'South Africa',
    official_name: 'the Republic of South Africa',
    sovereignty: 'UN member',
    code: 'ZA',
    triple_code: 'ZAF',
    numeric_code: '710',
    code_link: 'ISO 3166-2:ZA',
    domain: '.za',
  },
  // {
  //   name: 'South Georgia and the South Sandwich Islands',
  //   official_name: 'South Georgia and the South Sandwich Islands',
  //   sovereignty: 'United Kingdom',
  //   code: 'GS',
  //   triple_code: 'SGS',
  //   numeric_code: '239',
  //   code_link: 'ISO 3166-2:GS',
  //   domain: '.gs',
  // },
  {
    name: 'South Korea – See Korea, The Republic of.',
    official_name: '',
    sovereignty: '',
    code: '',
    triple_code: '',
    numeric_code: "''",
    code_link: '',
    domain: '',
  },
  {
    name: 'South Sudan',
    official_name: 'the Republic of South Sudan',
    sovereignty: 'UN member',
    code: 'SS',
    triple_code: 'SSD',
    numeric_code: '728',
    code_link: 'ISO 3166-2:SS',
    domain: '.ss',
  },
  {
    name: 'Spain',
    official_name: 'the Kingdom of Spain',
    sovereignty: 'UN member',
    code: 'ES',
    triple_code: 'ESP',
    numeric_code: '724',
    code_link: 'ISO 3166-2:ES',
    domain: '.es',
  },
  {
    name: 'Sri Lanka',
    official_name: 'the Democratic Socialist Republic of Sri Lanka',
    sovereignty: 'UN member',
    code: 'LK',
    triple_code: 'LKA',
    numeric_code: '144',
    code_link: 'ISO 3166-2:LK',
    domain: '.lk',
  },
  {
    name: 'Sudan (the)',
    official_name: 'the Republic of the Sudan',
    sovereignty: 'UN member',
    code: 'SD',
    triple_code: 'SDN',
    numeric_code: '729',
    code_link: 'ISO 3166-2:SD',
    domain: '.sd',
  },
  {
    name: 'Suriname',
    official_name: 'the Republic of Suriname',
    sovereignty: 'UN member',
    code: 'SR',
    triple_code: 'SUR',
    numeric_code: '740',
    code_link: 'ISO 3166-2:SR',
    domain: '.sr',
  },
  // {
  //   name: 'Svalbard\nJan Mayen',
  //   official_name: 'Svalbard and Jan Mayen[c]',
  //   sovereignty: 'Norway',
  //   code: 'SJ',
  //   triple_code: 'SJM',
  //   numeric_code: '744',
  //   code_link: 'ISO 3166-2:SJ',
  //   domain: '[ab]',
  // },
  {
    name: 'Sweden',
    official_name: 'the Kingdom of Sweden',
    sovereignty: 'UN member',
    code: 'SE',
    triple_code: 'SWE',
    numeric_code: '752',
    code_link: 'ISO 3166-2:SE',
    domain: '.se',
  },
  {
    name: 'Switzerland',
    official_name: 'the Swiss Confederation',
    sovereignty: 'UN member',
    code: 'CH',
    triple_code: 'CHE',
    numeric_code: '756',
    code_link: 'ISO 3166-2:CH',
    domain: '.ch',
  },
  {
    name: 'Syrian Arab Republic (the)[ac]',
    official_name: 'the Syrian Arab Republic',
    sovereignty: 'UN member',
    code: 'SY',
    triple_code: 'SYR',
    numeric_code: '760',
    code_link: 'ISO 3166-2:SY',
    domain: '.sy',
  },
  {
    name: 'Taiwan (Province of China)[ad]',
    official_name: 'the Republic of China[c][d]',
    sovereignty: 'Disputed[ae]',
    code: 'TW',
    triple_code: 'TWN',
    numeric_code: '158',
    code_link: 'ISO 3166-2:TW',
    domain: '.tw',
  },
  {
    name: 'Tajikistan',
    official_name: 'the Republic of Tajikistan',
    sovereignty: 'UN member',
    code: 'TJ',
    triple_code: 'TJK',
    numeric_code: '762',
    code_link: 'ISO 3166-2:TJ',
    domain: '.tj',
  },
  {
    name: 'Tanzania, the United Republic of',
    official_name: 'the United Republic of Tanzania',
    sovereignty: 'UN member',
    code: 'TZ',
    triple_code: 'TZA',
    numeric_code: '834',
    code_link: 'ISO 3166-2:TZ',
    domain: '.tz',
  },
  {
    name: 'Thailand',
    official_name: 'the Kingdom of Thailand',
    sovereignty: 'UN member',
    code: 'TH',
    triple_code: 'THA',
    numeric_code: '764',
    code_link: 'ISO 3166-2:TH',
    domain: '.th',
  },
  {
    name: 'Timor-Leste[af]',
    official_name: 'the Democratic Republic of Timor-Leste',
    sovereignty: 'UN member',
    code: 'TL',
    triple_code: 'TLS',
    numeric_code: '626',
    code_link: 'ISO 3166-2:TL',
    domain: '.tl',
  },
  {
    name: 'Togo',
    official_name: 'the Togolese Republic',
    sovereignty: 'UN member',
    code: 'TG',
    triple_code: 'TGO',
    numeric_code: '768',
    code_link: 'ISO 3166-2:TG',
    domain: '.tg',
  },
  // {
  //   name: 'Tokelau',
  //   official_name: 'Tokelau[c]',
  //   sovereignty: 'New Zealand',
  //   code: 'TK',
  //   triple_code: 'TKL',
  //   numeric_code: '772',
  //   code_link: 'ISO 3166-2:TK',
  //   domain: '.tk',
  // },
  {
    name: 'Tonga',
    official_name: 'the Kingdom of Tonga',
    sovereignty: 'UN member',
    code: 'TO',
    triple_code: 'TON',
    numeric_code: '776',
    code_link: 'ISO 3166-2:TO',
    domain: '.to',
  },
  {
    name: 'Trinidad and Tobago',
    official_name: 'the Republic of Trinidad and Tobago',
    sovereignty: 'UN member',
    code: 'TT',
    triple_code: 'TTO',
    numeric_code: '780',
    code_link: 'ISO 3166-2:TT',
    domain: '.tt',
  },
  {
    name: 'Tunisia',
    official_name: 'the Republic of Tunisia',
    sovereignty: 'UN member',
    code: 'TN',
    triple_code: 'TUN',
    numeric_code: '788',
    code_link: 'ISO 3166-2:TN',
    domain: '.tn',
  },
  {
    name: 'Türkiye[ag]',
    official_name: 'the Republic of Türkiye',
    sovereignty: 'UN member',
    code: 'TR',
    triple_code: 'TUR',
    numeric_code: '792',
    code_link: 'ISO 3166-2:TR',
    domain: '.tr',
  },
  {
    name: 'Turkmenistan',
    official_name: 'Turkmenistan[c]',
    sovereignty: 'UN member',
    code: 'TM',
    triple_code: 'TKM',
    numeric_code: '795',
    code_link: 'ISO 3166-2:TM',
    domain: '.tm',
  },
  {
    name: 'Turks and Caicos Islands (the)',
    official_name: 'the Turks and Caicos Islands[c]',
    sovereignty: 'United Kingdom',
    code: 'TC',
    triple_code: 'TCA',
    numeric_code: '796',
    code_link: 'ISO 3166-2:TC',
    domain: '.tc',
  },
  // {
  //   name: 'Tuvalu',
  //   official_name: 'Tuvalu[c]',
  //   sovereignty: 'UN member',
  //   code: 'TV',
  //   triple_code: 'TUV',
  //   numeric_code: '798',
  //   code_link: 'ISO 3166-2:TV',
  //   domain: '.tv',
  // },
  {
    name: 'Uganda',
    official_name: 'the Republic of Uganda',
    sovereignty: 'UN member',
    code: 'UG',
    triple_code: 'UGA',
    numeric_code: '800',
    code_link: 'ISO 3166-2:UG',
    domain: '.ug',
  },
  {
    name: 'Ukraine[c]',
    official_name: 'Ukraine',
    sovereignty: 'UN member',
    code: 'UA',
    triple_code: 'UKR',
    numeric_code: '804',
    code_link: 'ISO 3166-2:UA',
    domain: '.ua',
  },
  {
    name: 'United Arab Emirates (the)',
    official_name: 'the United Arab Emirates',
    sovereignty: 'UN member',
    code: 'AE',
    triple_code: 'ARE',
    numeric_code: '784',
    code_link: 'ISO 3166-2:AE',
    domain: '.ae',
  },
  {
    name: 'United Kingdom of Great Britain and Northern Ireland (the)',
    official_name: 'the United Kingdom of Great Britain and Northern Ireland',
    sovereignty: 'UN member',
    code: 'GB',
    triple_code: 'GBR',
    numeric_code: '826',
    code_link: 'ISO 3166-2:GB',
    domain: '- .gb\n   - .uk\n   [ah]',
  },
  // {
  //   name: 'United States Minor Outlying Islands (the)[13][ai]',
  //   official_name:
  //     'United States Pacific Island Wildlife Refuges,[14]Navassa Island, and \nWake Island[c][d]',
  //   sovereignty: 'United States',
  //   code: 'UM',
  //   triple_code: 'UMI',
  //   numeric_code: '581',
  //   code_link: 'ISO 3166-2:UM',
  //   domain: '[aj]',
  // },
  {
    name: 'United States of America (the)',
    official_name: 'the United States of America',
    sovereignty: 'UN member',
    code: 'US',
    triple_code: 'USA',
    numeric_code: '840',
    code_link: 'ISO 3166-2:US',
    domain: '.us',
  },
  {
    name: 'Uruguay',
    official_name: 'the Oriental Republic of Uruguay',
    sovereignty: 'UN member',
    code: 'UY',
    triple_code: 'URY',
    numeric_code: '858',
    code_link: 'ISO 3166-2:UY',
    domain: '.uy',
  },
  {
    name: 'Uzbekistan',
    official_name: 'the Republic of Uzbekistan',
    sovereignty: 'UN member',
    code: 'UZ',
    triple_code: 'UZB',
    numeric_code: '860',
    code_link: 'ISO 3166-2:UZ',
    domain: '.uz',
  },
  {
    name: 'Vanuatu',
    official_name: 'the Republic of Vanuatu',
    sovereignty: 'UN member',
    code: 'VU',
    triple_code: 'VUT',
    numeric_code: '548',
    code_link: 'ISO 3166-2:VU',
    domain: '.vu',
  },
  {
    name: 'Vatican City – See Holy See, The.',
    official_name: '',
    sovereignty: '',
    code: '',
    triple_code: '',
    numeric_code: "''",
    code_link: '',
    domain: '',
  },
  {
    name: 'Venezuela (Bolivarian Republic of)',
    official_name: 'the Bolivarian Republic of Venezuela',
    sovereignty: 'UN member',
    code: 'VE',
    triple_code: 'VEN',
    numeric_code: '862',
    code_link: 'ISO 3166-2:VE',
    domain: '.ve',
  },
  {
    name: 'Viet Nam[ak]',
    official_name: 'the Socialist Republic of Viet Nam',
    sovereignty: 'UN member',
    code: 'VN',
    triple_code: 'VNM',
    numeric_code: '704',
    code_link: 'ISO 3166-2:VN',
    domain: '.vn',
  },
  {
    name: 'Virgin Islands (British)[al]',
    official_name: 'the Virgin Islands[d]',
    sovereignty: 'United Kingdom',
    code: 'VG',
    triple_code: 'VGB',
    numeric_code: '92',
    code_link: 'ISO 3166-2:VG',
    domain: '.vg',
  },
  {
    name: 'Virgin Islands (U.S.)[am]',
    official_name: 'the Virgin Islands of the United States',
    sovereignty: 'United States',
    code: 'VI',
    triple_code: 'VIR',
    numeric_code: '850',
    code_link: 'ISO 3166-2:VI',
    domain: '.vi',
  },
  // {
  //   name: 'Wallis and Futuna',
  //   official_name: 'the Territory of the Wallis and Futuna Islands',
  //   sovereignty: 'France',
  //   code: 'WF',
  //   triple_code: 'WLF',
  //   numeric_code: '876',
  //   code_link: 'ISO 3166-2:WF',
  //   domain: '.wf',
  // },
  {
    name: 'Western Sahara[an]',
    official_name: 'the Sahrawi Arab Democratic Republic[c][d]',
    sovereignty: 'Disputed[ao]',
    code: 'EH',
    triple_code: 'ESH',
    numeric_code: '732',
    code_link: 'ISO 3166-2:EH',
    domain: '[ap]',
  },
  {
    name: 'Yemen',
    official_name: 'the Republic of Yemen',
    sovereignty: 'UN member',
    code: 'YE',
    triple_code: 'YEM',
    numeric_code: '887',
    code_link: 'ISO 3166-2:YE',
    domain: '.ye',
  },
  {
    name: 'Zambia',
    official_name: 'the Republic of Zambia',
    sovereignty: 'UN member',
    code: 'ZM',
    triple_code: 'ZMB',
    numeric_code: '894',
    code_link: 'ISO 3166-2:ZM',
    domain: '.zm',
  },
  {
    name: 'Zimbabwe',
    official_name: 'the Republic of Zimbabwe',
    sovereignty: 'UN member',
    code: 'ZW',
    triple_code: 'ZWE',
    numeric_code: '716',
    code_link: 'ISO 3166-2:ZW',
    domain: '.zw',
  },
] as const;

const nameRegex = /\(.+\)|\[.+\]/g;

type InferredCountry = (typeof country_data)[number];

export type CountryCode = Exclude<(typeof country_data)[number]['code'], ''>;
export type Country = Omit<Record<keyof InferredCountry, string>, 'code'> & {
  code: CountryCode;
  path: string;
};

export const country_list: Country[] = country_data
  .filter((c) => {
    if (c.code === '') {
      return false;
    }
    return true;
  })
  .map<Country>((c) => {
    if (c.code === '') {
      throw new Error('Missing country code.');
    }
    const country: Country = {
      ...(c as Country),
      name: (c.name as string).replaceAll(nameRegex, '').trim(),
      official_name: (c.official_name as string)
        .replaceAll(nameRegex, '')
        .trim(),
      path: country_paths[c.code],
    };
    return country;
  });

export const country_by_code = country_list.reduce(
  (acc, c) => {
    acc[c.code] = c;
    return acc;
  },
  {} as Record<CountryCode, Country>,
);
