const currencies = [
  {
    state: 'Afghanistan',
    currency: 'Afghan afghani',
    symbol: '؋‎',
    iso_code: 'AFN',
    fractional_unit: 'Pul',
  },
  {
    state: 'Akrotiri and Dhekelia',
    currency: 'Euro',
    symbol: '€',
    iso_code: 'EUR',
    fractional_unit: 'Cent',
  },
  {
    state: 'Albania',
    currency: 'Albanian lek',
    symbol: 'L',
    iso_code: 'ALL',
    fractional_unit: 'Qintar',
  },
  {
    state: 'Algeria',
    currency: 'Algerian dinar',
    symbol: 'DA',
    iso_code: 'DZD',
    fractional_unit: 'Centime',
  },
  {
    state: 'Western Sahara',
    currency: 'Algerian dinar',
    symbol: 'DA',
    iso_code: 'DZD',
    fractional_unit: 'Centime',
  },
  {
    state: 'Andorra',
    currency: 'Euro',
    symbol: '€',
    iso_code: 'EUR',
    fractional_unit: 'Cent',
  },
  {
    state: 'Angola',
    currency: 'Angolan kwanza',
    symbol: 'Kz',
    iso_code: 'AOA',
    fractional_unit: 'Cêntimo',
  },
  {
    state: 'Anguilla',
    currency: 'Eastern Caribbean dollar',
    symbol: 'EC$',
    iso_code: 'XCD',
    fractional_unit: 'Cent',
  },
  {
    state: 'Antigua and Barbuda',
    currency: 'Eastern Caribbean dollar',
    symbol: 'EC$',
    iso_code: 'XCD',
    fractional_unit: 'Cent',
  },
  {
    state: 'Argentina',
    currency: 'Argentine peso',
    symbol: '$',
    iso_code: 'ARS',
    fractional_unit: 'Centavo',
  },
  {
    state: 'Armenia',
    currency: 'Armenian dram',
    symbol: '֏',
    iso_code: 'AMD',
    fractional_unit: 'Luma',
  },
  {
    state: 'Aruba',
    currency: 'Aruban florin',
    symbol: 'ƒ',
    iso_code: 'AWG',
    fractional_unit: 'Cent',
  },
  {
    state: 'Ascension Island',
    currency: 'Saint Helena pound',
    symbol: '£',
    iso_code: 'SHP',
    fractional_unit: 'Penny',
  },
  {
    state: 'Australia',
    currency: 'Australian dollar',
    symbol: '$',
    iso_code: 'AUD',
    fractional_unit: 'Cent',
  },
  {
    state: 'Austria',
    currency: 'Euro',
    symbol: '€',
    iso_code: 'EUR',
    fractional_unit: 'Cent',
  },
  {
    state: 'Azerbaijan',
    currency: 'Azerbaijani manat',
    symbol: '₼',
    iso_code: 'AZN',
    fractional_unit: 'Qəpik',
  },
  {
    state: 'Bahamas',
    currency: 'Bahamian dollar',
    symbol: '$',
    iso_code: 'BSD',
    fractional_unit: 'Cent',
  },
  {
    state: 'Bahrain',
    currency: 'Bahraini dinar',
    symbol: 'BD',
    iso_code: 'BHD',
    fractional_unit: 'Fils',
  },
  {
    state: 'Bangladesh',
    currency: 'Bangladeshi taka',
    symbol: '৳',
    iso_code: 'BDT',
    fractional_unit: 'Poisha',
  },
  {
    state: 'Barbados',
    currency: 'Barbadian dollar',
    symbol: '$',
    iso_code: 'BBD',
    fractional_unit: 'Cent',
  },
  {
    state: 'Belarus',
    currency: 'Belarusian ruble',
    symbol: 'Br',
    iso_code: 'BYN',
    fractional_unit: 'Kopeck',
  },
  {
    state: 'Belgium',
    currency: 'Euro',
    symbol: '€',
    iso_code: 'EUR',
    fractional_unit: 'Cent',
  },
  {
    state: 'Belize',
    currency: 'Belize dollar',
    symbol: '$',
    iso_code: 'BZD',
    fractional_unit: 'Cent',
  },
  {
    state: 'Benin',
    currency: 'West African CFA franc',
    symbol: 'F.CFA',
    iso_code: 'XOF',
    fractional_unit: 'Centime',
  },
  {
    state: 'Bermuda',
    currency: 'Bermudian dollar',
    symbol: '$',
    iso_code: 'BMD',
    fractional_unit: 'Cent',
  },
  {
    state: 'Bhutan',
    currency: 'Bhutanese ngultrum[F]',
    symbol: 'Nu',
    iso_code: 'BTN',
    fractional_unit: 'Chetrum',
  },
  {
    state: 'Bhutan',
    currency: 'Indian rupee',
    symbol: '₹',
    iso_code: 'INR',
    fractional_unit: 'Paisa',
  },
  {
    state: 'Bolivia',
    currency: 'Bolivian boliviano',
    symbol: 'Bs',
    iso_code: 'BOB',
    fractional_unit: 'Centavo',
  },
  {
    state: 'Bonaire',
    currency: 'United States dollar[G]',
    symbol: '$',
    iso_code: 'USD',
    fractional_unit: 'Cent',
  },
  {
    state: 'Bosnia and Herzegovina',
    currency: 'Bosnia and Herzegovina convertible mark',
    symbol: 'KM',
    iso_code: 'BAM',
    fractional_unit: 'Fening',
  },
  {
    state: 'Botswana',
    currency: 'Botswana pula',
    symbol: 'P',
    iso_code: 'BWP',
    fractional_unit: 'Thebe',
  },
  {
    state: 'Brazil',
    currency: 'Brazilian real',
    symbol: 'R$',
    iso_code: 'BRL',
    fractional_unit: 'Centavo',
  },
  {
    state: 'British Virgin Islands',
    currency: 'United States dollar',
    symbol: '$',
    iso_code: 'USD',
    fractional_unit: 'Cent',
  },
  {
    state: 'Brunei',
    currency: 'Brunei dollar',
    symbol: '$',
    iso_code: 'BND',
    fractional_unit: 'Sen',
  },
  {
    state: 'Brunei',
    currency: 'Singapore dollar',
    symbol: '$',
    iso_code: 'SGD',
    fractional_unit: 'Cent',
  },
  {
    state: 'Bulgaria',
    currency: 'Bulgarian lev',
    symbol: 'lv.',
    iso_code: 'BGN',
    fractional_unit: 'Stotinka',
  },
  {
    state: 'Burkina Faso',
    currency: 'West African CFA franc',
    symbol: 'F.CFA',
    iso_code: 'XOF',
    fractional_unit: 'Centime',
  },
  {
    state: 'Burundi',
    currency: 'Burundian franc',
    symbol: 'FBu',
    iso_code: 'BIF',
    fractional_unit: 'Centime',
  },
  {
    state: 'Cambodia',
    currency: 'Cambodian riel',
    symbol: '៛',
    iso_code: 'KHR',
    fractional_unit: 'Sen',
  },
  {
    state: 'Cameroon',
    currency: 'Central African CFA franc',
    symbol: 'F.CFA',
    iso_code: 'XAF',
    fractional_unit: 'Centime',
  },
  {
    state: 'Canada',
    currency: 'Canadian dollar',
    symbol: '$',
    iso_code: 'CAD',
    fractional_unit: 'Cent',
  },
  {
    state: 'Cabo Verde / Cape Verde',
    currency: 'Cabo Verdean escudo',
    symbol: '',
    iso_code: 'CVE',
    fractional_unit: 'Centavo',
  },
  {
    state: 'Cayman Islands',
    currency: 'Cayman Islands dollar',
    symbol: '$',
    iso_code: 'KYD',
    fractional_unit: 'Cent',
  },
  {
    state: 'Central African Republic',
    currency: 'Central African CFA franc',
    symbol: 'F.CFA',
    iso_code: 'XAF',
    fractional_unit: 'Centime',
  },
  {
    state: 'Chad',
    currency: 'Central African CFA franc',
    symbol: 'F.CFA',
    iso_code: 'XAF',
    fractional_unit: 'Centime',
  },
  {
    state: 'Chile',
    currency: 'Chilean peso',
    symbol: '$',
    iso_code: 'CLP',
    fractional_unit: 'Centavo',
  },
  {
    state: 'China',
    currency: 'Renminbi',
    symbol: '¥',
    iso_code: 'CNY',
    fractional_unit: 'Jiao[I]',
  },
  {
    state: 'Colombia',
    currency: 'Colombian peso',
    symbol: '$',
    iso_code: 'COP',
    fractional_unit: 'Centavo',
  },
  {
    state: 'Comoros',
    currency: 'Comorian franc',
    symbol: 'FC',
    iso_code: 'KMF',
    fractional_unit: 'Centime',
  },
  {
    state: 'Democratic Republic of the Congo',
    currency: 'Congolese franc',
    symbol: 'FC',
    iso_code: 'CDF',
    fractional_unit: 'Centime',
  },
  {
    state: 'Congo',
    currency: 'Central African CFA franc',
    symbol: 'F.CFA',
    iso_code: 'XAF',
    fractional_unit: 'Centime',
  },
  {
    state: 'Cook Islands',
    currency: 'New Zealand dollar',
    symbol: '$',
    iso_code: 'NZD',
    fractional_unit: 'Cent',
  },
  {
    state: 'Costa Rica',
    currency: 'Costa Rican colón',
    symbol: '₡',
    iso_code: 'CRC',
    fractional_unit: 'Céntimo',
  },
  {
    state: "Côte d'Ivoire",
    currency: 'West African CFA franc',
    symbol: 'F.CFA',
    iso_code: 'XOF',
    fractional_unit: 'Centime',
  },
  {
    state: 'Croatia',
    currency: 'Euro',
    symbol: '€',
    iso_code: 'EUR',
    fractional_unit: 'Cent',
  },
  {
    state: 'Cuba',
    currency: 'Cuban peso',
    symbol: '$',
    iso_code: 'CUP',
    fractional_unit: 'Centavo',
  },
  {
    state: 'Curaçao',
    currency: 'Caribbean guilder',
    symbol: 'Cg',
    iso_code: 'XCG',
    fractional_unit: 'Cent',
  },
  {
    state: 'Cyprus',
    currency: 'Euro',
    symbol: '€',
    iso_code: 'EUR',
    fractional_unit: 'Cent',
  },
  {
    state: 'Czechia',
    currency: 'Czech koruna',
    symbol: 'Kč',
    iso_code: 'CZK',
    fractional_unit: 'Heller',
  },
  {
    state: 'Denmark',
    currency: 'Danish krone',
    symbol: 'kr',
    iso_code: 'DKK',
    fractional_unit: 'Øre',
  },
  {
    state: 'Djibouti',
    currency: 'Djiboutian franc',
    symbol: 'Fdj',
    iso_code: 'DJF',
    fractional_unit: 'Centime',
  },
  {
    state: 'Dominica',
    currency: 'Eastern Caribbean dollar',
    symbol: 'EC$',
    iso_code: 'XCD',
    fractional_unit: 'Cent',
  },
  {
    state: 'Dominican Republic',
    currency: 'Dominican peso',
    symbol: '$',
    iso_code: 'DOP',
    fractional_unit: 'Centavo',
  },
  {
    state: 'Ecuador',
    currency: 'United States dollar',
    symbol: '$',
    iso_code: 'USD',
    fractional_unit: 'Centavo',
  },
  {
    state: 'Egypt',
    currency: 'Egyptian pound',
    symbol: 'LE',
    iso_code: 'EGP',
    fractional_unit: 'Piastre[B]',
  },
  {
    state: 'Palestine',
    currency: 'Egyptian pound',
    symbol: 'LE',
    iso_code: 'EGP',
    fractional_unit: 'Piastre[B]',
  },
  {
    state: 'El Salvador',
    currency: 'United States dollar',
    symbol: '$',
    iso_code: 'USD',
    fractional_unit: 'Cent',
  },
  {
    state: 'Equatorial Guinea',
    currency: 'Central African CFA franc',
    symbol: 'F.CFA',
    iso_code: 'XAF',
    fractional_unit: 'Centime',
  },
  {
    state: 'Eritrea',
    currency: 'Eritrean nakfa',
    symbol: 'Nkf',
    iso_code: 'ERN',
    fractional_unit: 'Cent',
  },
  {
    state: 'Estonia',
    currency: 'Euro',
    symbol: '€',
    iso_code: 'EUR',
    fractional_unit: 'Cent',
  },
  {
    state: 'Eswatini',
    currency: 'Swazi lilangeni',
    symbol: 'L or E (pl.)',
    iso_code: 'SZL',
    fractional_unit: 'Cent',
  },
  {
    state: 'Eswatini',
    currency: 'South African rand',
    symbol: 'R',
    iso_code: 'ZAR',
    fractional_unit: 'Cent',
  },
  {
    state: 'Ethiopia',
    currency: 'Ethiopian birr',
    symbol: 'Br',
    iso_code: 'ETB',
    fractional_unit: 'Santim',
  },
  {
    state: 'Falkland Islands',
    currency: 'Falkland Islands pound',
    symbol: '£',
    iso_code: 'FKP',
    fractional_unit: 'Penny',
  },
  {
    state: 'Falkland Islands',
    currency: 'Sterling',
    symbol: '£',
    iso_code: 'GBP',
    fractional_unit: 'Penny',
  },
  {
    state: 'Faroe Islands',
    currency: 'Danish krone',
    symbol: 'kr',
    iso_code: 'DKK',
    fractional_unit: 'Øre',
  },
  {
    state: 'Fiji',
    currency: 'Fijian dollar',
    symbol: '$',
    iso_code: 'FJD',
    fractional_unit: 'Cent',
  },
  {
    state: 'Finland',
    currency: 'Euro',
    symbol: '€',
    iso_code: 'EUR',
    fractional_unit: 'Cent',
  },
  {
    state: 'France',
    currency: 'Euro',
    symbol: '€',
    iso_code: 'EUR',
    fractional_unit: 'Cent',
  },
  {
    state: 'French Polynesia',
    currency: 'CFP franc',
    symbol: '₣',
    iso_code: 'XPF',
    fractional_unit: 'Centime',
  },
  {
    state: 'Gabon',
    currency: 'Central African CFA franc',
    symbol: 'F.CFA',
    iso_code: 'XAF',
    fractional_unit: 'Centime',
  },
  {
    state: 'Gambia',
    currency: 'Gambian dalasi',
    symbol: 'D',
    iso_code: 'GMD',
    fractional_unit: 'Butut',
  },
  {
    state: 'Georgia',
    currency: 'Georgian lari',
    symbol: '₾',
    iso_code: 'GEL',
    fractional_unit: 'Tetri',
  },
  {
    state: 'Germany',
    currency: 'Euro',
    symbol: '€',
    iso_code: 'EUR',
    fractional_unit: 'Cent',
  },
  {
    state: 'Ghana',
    currency: 'Ghanaian cedi',
    symbol: '₵',
    iso_code: 'GHS',
    fractional_unit: 'Pesewa',
  },
  {
    state: 'Gibraltar',
    currency: 'Gibraltar pound',
    symbol: '£',
    iso_code: 'GIP',
    fractional_unit: 'Penny',
  },
  {
    state: 'Gibraltar',
    currency: 'Sterling',
    symbol: '£',
    iso_code: 'GBP',
    fractional_unit: 'Penny',
  },
  {
    state: 'Greece',
    currency: 'Euro',
    symbol: '€',
    iso_code: 'EUR',
    fractional_unit: 'Cent',
  },
  {
    state: 'Greenland',
    currency: 'Danish krone',
    symbol: 'kr',
    iso_code: 'DKK',
    fractional_unit: 'Øre',
  },
  {
    state: 'Grenada',
    currency: 'Eastern Caribbean dollar',
    symbol: 'EC$',
    iso_code: 'XCD',
    fractional_unit: 'Cent',
  },
  {
    state: 'Guatemala',
    currency: 'Guatemalan quetzal',
    symbol: 'Q',
    iso_code: 'GTQ',
    fractional_unit: 'Centavo',
  },
  {
    state: 'Bailiwick of Guernsey',
    currency: 'Sterling',
    symbol: '£',
    iso_code: 'GBP',
    fractional_unit: 'Penny',
  },
  {
    state: 'Guinea',
    currency: 'Guinean franc',
    symbol: 'Fr',
    iso_code: 'GNF',
    fractional_unit: 'Centime',
  },
  {
    state: 'French Guiana',
    currency: 'Euro',
    symbol: '€',
    iso_code: 'EUR',
    fractional_unit: 'Cent',
  },
  {
    state: 'Réunion',
    currency: 'Euro',
    symbol: '€',
    iso_code: 'EUR',
    fractional_unit: 'Cent',
  },
  {
    state: 'Guadeloupe',
    currency: 'Euro',
    symbol: '€',
    iso_code: 'EUR',
    fractional_unit: 'Cent',
  },
  {
    state: 'Mayotte',
    currency: 'Euro',
    symbol: '€',
    iso_code: 'EUR',
    fractional_unit: 'Cent',
  },
  {
    state: 'Martinique',
    currency: 'Euro',
    symbol: '€',
    iso_code: 'EUR',
    fractional_unit: 'Cent',
  },
  {
    state: 'Guinea-Bissau',
    currency: 'West African CFA franc',
    symbol: 'F.CFA',
    iso_code: 'XOF',
    fractional_unit: 'Centime',
  },
  {
    state: 'Guyana',
    currency: 'Guyanese dollar',
    symbol: '$',
    iso_code: 'GYD',
    fractional_unit: 'Cent',
  },
  {
    state: 'Haiti',
    currency: 'Haitian gourde',
    symbol: 'G',
    iso_code: 'HTG',
    fractional_unit: 'Centime',
  },
  {
    state: 'Honduras',
    currency: 'Honduran lempira',
    symbol: 'L',
    iso_code: 'HNL',
    fractional_unit: 'Centavo',
  },
  {
    state: 'Hong Kong',
    currency: 'Hong Kong dollar',
    symbol: '$',
    iso_code: 'HKD',
    fractional_unit: 'Cent',
  },
  {
    state: 'Hungary',
    currency: 'Hungarian forint',
    symbol: 'Ft',
    iso_code: 'HUF',
    fractional_unit: '*none*[J]',
  },
  {
    state: 'Iceland',
    currency: 'Icelandic króna',
    symbol: 'kr',
    iso_code: 'ISK',
    fractional_unit: 'Eyrir',
  },
  {
    state: 'India',
    currency: 'Indian rupee',
    symbol: '₹',
    iso_code: 'INR',
    fractional_unit: 'Paisa',
  },
  {
    state: 'Indonesia',
    currency: 'Indonesian rupiah',
    symbol: 'Rp',
    iso_code: 'IDR',
    fractional_unit: 'Sen',
  },
  {
    state: 'Iran',
    currency: 'Iranian rial',
    symbol: 'Rl or Rls (pl.)',
    iso_code: 'IRR',
    fractional_unit: 'Dinar',
  },
  {
    state: 'Iraq',
    currency: 'Iraqi dinar',
    symbol: 'ID',
    iso_code: 'IQD',
    fractional_unit: 'Fils',
  },
  {
    state: 'Ireland',
    currency: 'Euro',
    symbol: '€',
    iso_code: 'EUR',
    fractional_unit: 'Cent',
  },
  {
    state: 'Isle of Man',
    currency: 'Sterling',
    symbol: '£',
    iso_code: 'GBP',
    fractional_unit: 'Penny',
  },
  {
    state: 'Israel',
    currency: 'Israeli new shekel',
    symbol: '₪',
    iso_code: 'ILS',
    fractional_unit: 'Agora',
  },
  {
    state: 'Palestine',
    currency: 'Israeli new shekel',
    symbol: '₪',
    iso_code: 'ILS',
    fractional_unit: 'Agora',
  },
  {
    state: 'Italy',
    currency: 'Euro',
    symbol: '€',
    iso_code: 'EUR',
    fractional_unit: 'Cent',
  },
  {
    state: 'Jamaica',
    currency: 'Jamaican dollar',
    symbol: '$',
    iso_code: 'JMD',
    fractional_unit: 'Cent',
  },
  {
    state: 'Japan',
    currency: 'Japanese yen',
    symbol: '¥',
    iso_code: 'JPY',
    fractional_unit: 'Sen[C]',
  },
  {
    state: 'Jersey',
    currency: 'Sterling',
    symbol: '£',
    iso_code: 'GBP',
    fractional_unit: 'Penny',
  },
  {
    state: 'Jordan',
    currency: 'Jordanian dinar',
    symbol: 'JD',
    iso_code: 'JOD',
    fractional_unit: 'Piastre[K]',
  },
  {
    state: 'Kazakhstan',
    currency: 'Kazakhstani tenge',
    symbol: '₸',
    iso_code: 'KZT',
    fractional_unit: 'Tıyn',
  },
  {
    state: 'Kenya',
    currency: 'Kenyan shilling',
    symbol: 'Sh or Shs (pl.)',
    iso_code: 'KES',
    fractional_unit: 'Cent',
  },
  {
    state: 'Kiribati',
    currency: 'Australian dollar',
    symbol: '$',
    iso_code: 'AUD',
    fractional_unit: 'Cent',
  },
  {
    state: 'North Korea',
    currency: 'North Korean won',
    symbol: '₩',
    iso_code: 'KPW',
    fractional_unit: 'Chon',
  },
  {
    state: 'South Korea',
    currency: 'South Korean won',
    symbol: '₩',
    iso_code: 'KRW',
    fractional_unit: 'Jeon',
  },
  {
    state: 'Kuwait',
    currency: 'Kuwaiti dinar',
    symbol: 'KD',
    iso_code: 'KWD',
    fractional_unit: 'Fils',
  },
  {
    state: 'Kyrgyzstan',
    currency: 'Kyrgyz som',
    symbol: '*⃀*',
    iso_code: 'KGS',
    fractional_unit: 'Tyiyn',
  },
  {
    state: 'Laos',
    currency: 'Lao kip',
    symbol: '₭',
    iso_code: 'LAK',
    fractional_unit: 'Att',
  },
  {
    state: 'Latvia',
    currency: 'Euro',
    symbol: '€',
    iso_code: 'EUR',
    fractional_unit: 'Cent',
  },
  {
    state: 'Lebanon',
    currency: 'Lebanese pound',
    symbol: 'LL',
    iso_code: 'LBP',
    fractional_unit: 'Piastre',
  },
  {
    state: 'Lesotho',
    currency: 'Lesotho loti',
    symbol: 'L or M (pl.)',
    iso_code: 'LSL',
    fractional_unit: 'Sente',
  },
  {
    state: 'Lesotho',
    currency: 'South African rand',
    symbol: 'R',
    iso_code: 'ZAR',
    fractional_unit: 'Cent',
  },
  {
    state: 'South Georgia and the South Sandwich Islands',
    currency: 'Falkland Islands pound',
    symbol: '£',
    iso_code: 'FKP',
    fractional_unit: 'Penny',
  },
  {
    state: 'South Georgia and the South Sandwich Islands',
    currency: 'Sterling',
    symbol: '£',
    iso_code: 'GBP',
    fractional_unit: 'Penny',
  },
  {
    state: 'Liberia',
    currency: 'Liberian dollar',
    symbol: '$',
    iso_code: 'LRD',
    fractional_unit: 'Cent',
  },
  {
    state: 'Liberia',
    currency: 'United States dollar',
    symbol: '$',
    iso_code: 'USD',
    fractional_unit: 'Cent',
  },
  {
    state: 'Libya',
    currency: 'Libyan dinar',
    symbol: 'LD',
    iso_code: 'LYD',
    fractional_unit: 'Dirham',
  },
  {
    state: 'Liechtenstein',
    currency: 'Swiss franc',
    symbol: 'Fr',
    iso_code: 'CHF',
    fractional_unit: 'Rappen',
  },
  {
    state: 'Lithuania',
    currency: 'Euro',
    symbol: '€',
    iso_code: 'EUR',
    fractional_unit: 'Cent',
  },
  {
    state: 'Luxembourg',
    currency: 'Euro',
    symbol: '€',
    iso_code: 'EUR',
    fractional_unit: 'Cent',
  },
  {
    state: 'Macau',
    currency: 'Macanese pataca',
    symbol: '$ or ptc',
    iso_code: 'MOP',
    fractional_unit: 'Avo',
  },
  {
    state: 'Madagascar',
    currency: 'Malagasy ariary',
    symbol: 'Ar',
    iso_code: 'MGA',
    fractional_unit: 'Iraimbilanja',
  },
  {
    state: 'Malawi',
    currency: 'Malawian kwacha',
    symbol: 'K',
    iso_code: 'MWK',
    fractional_unit: 'Tambala',
  },
  {
    state: 'Malaysia',
    currency: 'Malaysian ringgit',
    symbol: 'RM',
    iso_code: 'MYR',
    fractional_unit: 'Sen',
  },
  {
    state: 'Maldives',
    currency: 'Maldivian rufiyaa',
    symbol: 'Rf',
    iso_code: 'MVR',
    fractional_unit: 'Laari',
  },
  {
    state: 'Mali',
    currency: 'West African CFA franc',
    symbol: 'F.CFA',
    iso_code: 'XOF',
    fractional_unit: 'Centime',
  },
  {
    state: 'Malta',
    currency: 'Euro',
    symbol: '€',
    iso_code: 'EUR',
    fractional_unit: 'Cent',
  },
  {
    state: 'Marshall Islands',
    currency: 'United States dollar',
    symbol: '$',
    iso_code: 'USD',
    fractional_unit: 'Cent',
  },
  {
    state: 'Mauritania',
    currency: 'Mauritanian ouguiya',
    symbol: 'UM',
    iso_code: 'MRU',
    fractional_unit: 'Khoums',
  },
  {
    state: 'Mauritius',
    currency: 'Mauritian rupee',
    symbol: 'Re or Rs (pl.)',
    iso_code: 'MUR',
    fractional_unit: 'Cent',
  },
  {
    state: 'Mexico',
    currency: 'Mexican peso',
    symbol: '$',
    iso_code: 'MXN',
    fractional_unit: 'Centavo',
  },
  {
    state: 'Micronesia',
    currency: 'United States dollar',
    symbol: '$',
    iso_code: 'USD',
    fractional_unit: 'Cent',
  },
  {
    state: 'Moldova',
    currency: 'Moldovan leu',
    symbol: 'Leu or Lei (pl.)',
    iso_code: 'MDL',
    fractional_unit: 'Ban',
  },
  {
    state: 'Monaco',
    currency: 'Euro',
    symbol: '€',
    iso_code: 'EUR',
    fractional_unit: 'Cent',
  },
  {
    state: 'Mongolia',
    currency: 'Mongolian tögrög',
    symbol: '₮',
    iso_code: 'MNT',
    fractional_unit: 'Möngö',
  },
  {
    state: 'Montenegro',
    currency: 'Euro',
    symbol: '€',
    iso_code: 'EUR',
    fractional_unit: 'Cent',
  },
  {
    state: 'Montserrat',
    currency: 'Eastern Caribbean dollar',
    symbol: 'EC$',
    iso_code: 'XCD',
    fractional_unit: 'Cent',
  },
  {
    state: 'Morocco',
    currency: 'Moroccan dirham',
    symbol: 'DH',
    iso_code: 'MAD',
    fractional_unit: 'Centime',
  },
  {
    state: 'Western Sahara',
    currency: 'Moroccan dirham',
    symbol: 'DH',
    iso_code: 'MAD',
    fractional_unit: 'Centime',
  },
  {
    state: 'Mozambique',
    currency: 'Mozambican metical',
    symbol: 'Mt',
    iso_code: 'MZN',
    fractional_unit: 'Centavo',
  },
  {
    state: 'Myanmar',
    currency: 'Burmese kyat',
    symbol: 'K or Ks (pl.)',
    iso_code: 'MMK',
    fractional_unit: 'Pya',
  },
  {
    state: 'Namibia',
    currency: 'Namibian dollar',
    symbol: '$',
    iso_code: 'NAD',
    fractional_unit: 'Cent',
  },
  {
    state: 'Namibia',
    currency: 'South African rand',
    symbol: 'R',
    iso_code: 'ZAR',
    fractional_unit: 'Cent',
  },
  {
    state: 'Nauru',
    currency: 'Australian dollar',
    symbol: '$',
    iso_code: 'AUD',
    fractional_unit: 'Cent',
  },
  {
    state: 'Nepal',
    currency: 'Nepalese rupee',
    symbol: 'रु',
    iso_code: 'NPR',
    fractional_unit: 'Paisa',
  },
  {
    state: 'Netherlands',
    currency: 'Euro',
    symbol: '€',
    iso_code: 'EUR',
    fractional_unit: 'Cent',
  },
  {
    state: 'New Caledonia',
    currency: 'CFP franc',
    symbol: '₣',
    iso_code: 'XPF',
    fractional_unit: 'Centime',
  },
  {
    state: 'New Zealand',
    currency: 'New Zealand dollar',
    symbol: '$',
    iso_code: 'NZD',
    fractional_unit: 'Cent',
  },
  {
    state: 'Nicaragua',
    currency: 'Nicaraguan córdoba',
    symbol: 'C$',
    iso_code: 'NIO',
    fractional_unit: 'Centavo',
  },
  {
    state: 'Niger',
    currency: 'West African CFA franc',
    symbol: 'F.CFA',
    iso_code: 'XOF',
    fractional_unit: 'Centime',
  },
  {
    state: 'Nigeria',
    currency: 'Nigerian naira',
    symbol: '₦',
    iso_code: 'NGN',
    fractional_unit: 'Kobo',
  },
  {
    state: 'Niue',
    currency: 'New Zealand dollar',
    symbol: '$',
    iso_code: 'NZD',
    fractional_unit: 'Cent',
  },
  {
    state: 'North Macedonia',
    currency: 'Macedonian denar',
    symbol: 'DEN',
    iso_code: 'MKD',
    fractional_unit: 'Deni',
  },
  {
    state: 'Norway',
    currency: 'Norwegian krone',
    symbol: 'kr',
    iso_code: 'NOK',
    fractional_unit: 'Øre',
  },
  {
    state: 'Oman',
    currency: 'Omani rial',
    symbol: 'RO',
    iso_code: 'OMR',
    fractional_unit: 'Baisa',
  },
  {
    state: 'Pakistan',
    currency: 'Pakistani rupee',
    symbol: 'Re or Rs (pl.)',
    iso_code: 'PKR',
    fractional_unit: 'Paisa',
  },
  {
    state: 'Palau',
    currency: 'United States dollar',
    symbol: '$',
    iso_code: 'USD',
    fractional_unit: 'Cent',
  },
  {
    state: 'Panama',
    currency: 'Panamanian balboa',
    symbol: 'B/',
    iso_code: 'PAB',
    fractional_unit: 'Centésimo',
  },
  {
    state: 'Panama',
    currency: 'United States dollar',
    symbol: '$',
    iso_code: 'USD',
    fractional_unit: 'Cent',
  },
  {
    state: 'Papua New Guinea',
    currency: 'Papua New Guinean kina',
    symbol: 'K',
    iso_code: 'PGK',
    fractional_unit: 'Toea',
  },
  {
    state: 'Paraguay',
    currency: 'Paraguayan guaraní',
    symbol: '₲',
    iso_code: 'PYG',
    fractional_unit: 'Céntimo',
  },
  {
    state: 'Peru',
    currency: 'Peruvian sol',
    symbol: 'S/',
    iso_code: 'PEN',
    fractional_unit: 'Céntimo',
  },
  {
    state: 'Philippines',
    currency: 'Philippine peso',
    symbol: '₱',
    iso_code: 'PHP',
    fractional_unit: 'Sentimo',
  },
  {
    state: 'Pitcairn',
    currency: 'New Zealand dollar',
    symbol: '$',
    iso_code: 'NZD',
    fractional_unit: 'Cent',
  },
  {
    state: 'Poland',
    currency: 'Polish złoty',
    symbol: 'zł',
    iso_code: 'PLN',
    fractional_unit: 'Grosz',
  },
  {
    state: 'Portugal',
    currency: 'Euro',
    symbol: '€',
    iso_code: 'EUR',
    fractional_unit: 'Cent',
  },
  {
    state: 'Qatar',
    currency: 'Qatari riyal',
    symbol: 'QR',
    iso_code: 'QAR',
    fractional_unit: 'Dirham',
  },
  {
    state: 'Romania',
    currency: 'Romanian leu',
    symbol: 'Leu or Lei (pl.)',
    iso_code: 'RON',
    fractional_unit: 'Ban',
  },
  {
    state: 'Russia',
    currency: 'Russian ruble',
    symbol: '₽',
    iso_code: 'RUB',
    fractional_unit: 'Kopeck',
  },
  {
    state: 'Rwanda',
    currency: 'Rwandan franc',
    symbol: 'FRw',
    iso_code: 'RWF',
    fractional_unit: 'Centime',
  },
  {
    state: 'Saba',
    currency: 'United States dollar[G]',
    symbol: '$',
    iso_code: 'USD',
    fractional_unit: 'Cent',
  },
  {
    state: 'Saint Helena',
    currency: 'Saint Helena pound',
    symbol: '£',
    iso_code: 'SHP',
    fractional_unit: 'Penny',
  },
  {
    state: 'Saint Helena',
    currency: 'Sterling',
    symbol: '£',
    iso_code: 'GBP',
    fractional_unit: 'Penny',
  },
  {
    state: 'Saint Kitts and Nevis',
    currency: 'Eastern Caribbean dollar',
    symbol: 'EC$',
    iso_code: 'XCD',
    fractional_unit: 'Cent',
  },
  {
    state: 'Saint Lucia',
    currency: 'Eastern Caribbean dollar',
    symbol: 'EC$',
    iso_code: 'XCD',
    fractional_unit: 'Cent',
  },
  {
    state: 'Saint Vincent and the Grenadines',
    currency: 'Eastern Caribbean dollar',
    symbol: 'EC$',
    iso_code: 'XCD',
    fractional_unit: 'Cent',
  },
  {
    state: 'Samoa',
    currency: 'Samoan tālā',
    symbol: '$',
    iso_code: 'WST',
    fractional_unit: 'Sene',
  },
  {
    state: 'San Marino',
    currency: 'Euro',
    symbol: '€',
    iso_code: 'EUR',
    fractional_unit: 'Cent',
  },
  {
    state: 'São Tomé and Príncipe',
    currency: 'São Tomé and Príncipe dobra',
    symbol: 'Db',
    iso_code: 'STN',
    fractional_unit: 'Cêntimo',
  },
  {
    state: 'Saudi Arabia',
    currency: 'Saudi riyal',
    symbol: '',
    iso_code: 'SAR',
    fractional_unit: 'Halala',
  },
  {
    state: 'Senegal',
    currency: 'West African CFA franc',
    symbol: 'F.CFA',
    iso_code: 'XOF',
    fractional_unit: 'Centime',
  },
  {
    state: 'Serbia',
    currency: 'Serbian dinar',
    symbol: 'DIN',
    iso_code: 'RSD',
    fractional_unit: 'Para',
  },
  {
    state: 'Seychelles',
    currency: 'Seychellois rupee',
    symbol: 'Re or Rs (pl.)',
    iso_code: 'SCR',
    fractional_unit: 'Cent',
  },
  {
    state: 'Sierra Leone',
    currency: 'Sierra Leonean leone',
    symbol: 'Le',
    iso_code: 'SLE',
    fractional_unit: 'Cent',
  },
  {
    state: 'Singapore',
    currency: 'Singapore dollar',
    symbol: '$',
    iso_code: 'SGD',
    fractional_unit: 'Cent',
  },
  {
    state: 'Singapore',
    currency: 'Brunei dollar',
    symbol: '$',
    iso_code: 'BND',
    fractional_unit: 'Sen',
  },
  {
    state: 'Sint Eustatius',
    currency: 'United States dollar[G]',
    symbol: '$',
    iso_code: 'USD',
    fractional_unit: 'Cent',
  },
  {
    state: 'Sint Maarten',
    currency: 'Caribbean guilder',
    symbol: 'Cg',
    iso_code: 'XCG',
    fractional_unit: 'Cent',
  },
  {
    state: 'Slovakia',
    currency: 'Euro',
    symbol: '€',
    iso_code: 'EUR',
    fractional_unit: 'Cent',
  },
  {
    state: 'Slovenia',
    currency: 'Euro',
    symbol: '€',
    iso_code: 'EUR',
    fractional_unit: 'Cent',
  },
  {
    state: 'Solomon Islands',
    currency: 'Solomon Islands dollar',
    symbol: '$',
    iso_code: 'SBD',
    fractional_unit: 'Cent',
  },
  {
    state: 'Somalia',
    currency: 'Somali shilling',
    symbol: 'Sh or Shs (pl.)',
    iso_code: 'SOS',
    fractional_unit: 'Cent',
  },
  {
    state: 'South Africa',
    currency: 'South African rand',
    symbol: 'R',
    iso_code: 'ZAR',
    fractional_unit: 'Cent',
  },
  {
    state: 'South Sudan',
    currency: 'South Sudanese pound',
    symbol: 'SS£',
    iso_code: 'SSP',
    fractional_unit: 'Piaster',
  },
  {
    state: 'Spain',
    currency: 'Euro',
    symbol: '€',
    iso_code: 'EUR',
    fractional_unit: 'Cent',
  },
  {
    state: 'Sri Lanka',
    currency: 'Sri Lankan rupee',
    symbol: 'Re or Rs (pl.)',
    iso_code: 'LKR',
    fractional_unit: 'Cent',
  },
  {
    state: 'Sudan',
    currency: 'Sudanese pound',
    symbol: 'LS',
    iso_code: 'SDG',
    fractional_unit: 'Piastre',
  },
  {
    state: 'Suriname',
    currency: 'Surinamese dollar',
    symbol: '$',
    iso_code: 'SRD',
    fractional_unit: 'Cent',
  },
  {
    state: 'Sweden',
    currency: 'Swedish krona',
    symbol: 'kr',
    iso_code: 'SEK',
    fractional_unit: 'Öre',
  },
  {
    state: 'Switzerland',
    currency: 'Swiss franc',
    symbol: 'Fr',
    iso_code: 'CHF',
    fractional_unit: 'Rappen[O]',
  },
  {
    state: 'Syrian Arab Republic',
    currency: 'Syrian pound',
    symbol: 'LS',
    iso_code: 'SYP',
    fractional_unit: 'Piastre',
  },
  {
    state: 'Taiwan',
    currency: 'New Taiwan dollar',
    symbol: '$',
    iso_code: 'TWD',
    fractional_unit: 'Cent',
  },
  {
    state: 'Tajikistan',
    currency: 'Tajikistani somoni',
    symbol: 'SM',
    iso_code: 'TJS',
    fractional_unit: 'Diram',
  },
  {
    state: 'Tanzania',
    currency: 'Tanzanian shilling',
    symbol: 'Sh or Shs (pl.)',
    iso_code: 'TZS',
    fractional_unit: 'Cent',
  },
  {
    state: 'Thailand',
    currency: 'Thai baht',
    symbol: '฿',
    iso_code: 'THB',
    fractional_unit: 'Satang',
  },
  {
    state: 'Timor-Leste',
    currency: 'United States dollar',
    symbol: '$',
    iso_code: 'USD',
    fractional_unit: 'Centavo',
  },
  {
    state: 'Togo',
    currency: 'West African CFA franc',
    symbol: 'F.CFA',
    iso_code: 'XOF',
    fractional_unit: 'Centime',
  },
  {
    state: 'Tonga',
    currency: 'Tongan paʻanga[P]',
    symbol: 'T$',
    iso_code: 'TOP',
    fractional_unit: 'Seniti',
  },
  {
    state: 'Trinidad and Tobago',
    currency: 'Trinidad and Tobago dollar',
    symbol: '$',
    iso_code: 'TTD',
    fractional_unit: 'Cent',
  },
  {
    state: 'Tunisia',
    currency: 'Tunisian dinar',
    symbol: 'DT',
    iso_code: 'TND',
    fractional_unit: 'Millime',
  },
  {
    state: 'Türkiye',
    currency: 'Turkish lira',
    symbol: '₺',
    iso_code: 'TRY',
    fractional_unit: 'Kuruş',
  },
  {
    state: 'Turkmenistan',
    currency: 'Turkmenistani manat',
    symbol: 'm',
    iso_code: 'TMT',
    fractional_unit: 'Tenge',
  },
  {
    state: 'Turks and Caicos Islands',
    currency: 'United States dollar',
    symbol: '$',
    iso_code: 'USD',
    fractional_unit: 'Cent',
  },
  {
    state: 'Tuvalu',
    currency: 'Australian dollar',
    symbol: '$',
    iso_code: 'AUD',
    fractional_unit: 'Cent',
  },
  {
    state: 'Uganda',
    currency: 'Ugandan shilling',
    symbol: 'Sh or Shs (pl.)',
    iso_code: 'UGX',
    fractional_unit: '',
  },
  {
    state: 'Ukraine',
    currency: 'Ukrainian hryvnia',
    symbol: '₴',
    iso_code: 'UAH',
    fractional_unit: 'Kopeck',
  },
  {
    state: 'United Arab Emirates',
    currency: 'United Arab Emirates dirham',
    symbol: '',
    iso_code: 'AED',
    fractional_unit: 'Fils',
  },
  {
    state: 'United Kingdom',
    currency: 'Sterling',
    symbol: '£',
    iso_code: 'GBP',
    fractional_unit: 'Penny',
  },
  {
    state: 'United States',
    currency: 'United States dollar',
    symbol: '$',
    iso_code: 'USD',
    fractional_unit: 'Cent[A]',
  },
  {
    state: 'U.S. Virgin Islands',
    currency: 'United States dollar',
    symbol: '$',
    iso_code: 'USD',
    fractional_unit: 'Cent[A]',
  },
  {
    state: 'Puerto Rico',
    currency: 'United States dollar',
    symbol: '$',
    iso_code: 'USD',
    fractional_unit: 'Cent[A]',
  },
  {
    state: 'Uruguay',
    currency: 'Uruguayan peso',
    symbol: '$',
    iso_code: 'UYU',
    fractional_unit: 'Centésimo',
  },
  {
    state: 'Uzbekistan',
    currency: 'Uzbekistani sum',
    symbol: 'Sʻ',
    iso_code: 'UZS',
    fractional_unit: 'Tiyin',
  },
  {
    state: 'Vanuatu',
    currency: 'Vanuatu vatu',
    symbol: 'VT',
    iso_code: 'VUV',
    fractional_unit: 'Cent',
  },
  {
    state: 'Vatican City',
    currency: 'Euro',
    symbol: '€',
    iso_code: 'EUR',
    fractional_unit: 'Cent',
  },
  {
    state: 'Venezuela',
    currency: 'Venezuelan sovereign bolívar',
    symbol: 'Bs.S',
    iso_code: 'VES',
    fractional_unit: 'Céntimo',
  },
  {
    state: 'Venezuela',
    currency: 'Venezuelan digital bolívar',
    symbol: 'Bs.D',
    iso_code: 'VED',
    fractional_unit: 'Céntimo',
  },
  {
    state: 'Vietnam',
    currency: 'Vietnamese đồng',
    symbol: '₫',
    iso_code: 'VND',
    fractional_unit: 'Hào[Q]',
  },
  {
    state: 'Wallis and Futuna',
    currency: 'CFP franc',
    symbol: '₣',
    iso_code: 'XPF',
    fractional_unit: 'Centime',
  },
  {
    state: 'Yemen',
    currency: 'Yemeni rial',
    symbol: 'Rl or Rls (pl.)',
    iso_code: 'YER',
    fractional_unit: 'Fils',
  },
  {
    state: 'Zambia',
    currency: 'Zambian kwacha',
    symbol: 'K',
    iso_code: 'ZMW',
    fractional_unit: 'Ngwee',
  },
  {
    state: 'Zimbabwe',
    currency: 'Zimbabwe gold',
    symbol: 'ZiG',
    iso_code: 'ZWG',
    fractional_unit: '',
  },
] as const;

export default currencies;
