export interface Country {
  name: string;
  other_names?: string[];
  /** URL to svg. */
  flag: string;
  vector: string;
}

export const country_ids = [
  'ae',
  'ad',
  'af',
  'ag',
  'ai',
  'al',
  'am',
  'ao',
  'aq',
  'ar',
  'as',
  'at',
  'au',
  'aw',
  'ax',
  'az',
  'ba',
  'bb',
  'bd',
  'be',
  'bf',
  'bg',
  'bh',
  'bi',
  'bj',
  'bl',
  'bm',
  'bn',
  'bo',
  'bq',
  'br',
  'bs',
  'bt',
  'bv',
  'bw',
  'by',
  'bz',
  'ca',
  'cc',
  'cd',
  'cf',
  'cg',
  'ch',
  'ci',
  'ck',
  'cl',
  'cm',
  'cn',
  'co',
  'cr',
  'cu',
  'cv',
  'cw',
  'cx',
  'cy',
  'cz',
  'de',
  'dj',
  'dk',
  'dm',
  'do',
  'dz',
  'ec',
  'ee',
  'eg',
  'eh',
  'er',
  'es',
  'et',
  'eu',
  'fi',
  'fj',
  'fk',
  'fm',
  'fo',
  'fr',
  'ga',
  'gb',
  'gb-eng',
  'gb-nir',
  'gb-sct',
  'gb-wls',
  'gd',
  'ge',
  'gf',
  'gg',
  'gh',
  'gi',
  'gl',
  'gm',
  'gn',
  'gp',
  'gq',
  'gr',
  'gs',
  'gt',
  'gu',
  'gw',
  'gy',
  'hk',
  'hm',
  'hn',
  'hr',
  'ht',
  'hu',
  'id',
  'ie',
  'il',
  'im',
  'in',
  'io',
  'iq',
  'ir',
  'is',
  'it',
  'je',
  'jm',
  'jo',
  'jp',
  'ke',
  'kg',
  'kh',
  'ki',
  'km',
  'kn',
  'kp',
  'kr',
  'kw',
  'ky',
  'kz',
  'la',
  'lb',
  'lc',
  'li',
  'lk',
  'lr',
  'ls',
  'lt',
  'lu',
  'lv',
  'ly',
  'ma',
  'mc',
  'md',
  'me',
  'mf',
  'mg',
  'mh',
  'mk',
  'ml',
  'mm',
  'mn',
  'mo',
  'mp',
  'mq',
  'mr',
  'ms',
  'mt',
  'mu',
  'mv',
  'mw',
  'mx',
  'my',
  'mz',
  'na',
  'nc',
  'ne',
  'nf',
  'ng',
  'ni',
  'nl',
  'no',
  'np',
  'nr',
  'nu',
  'nz',
  'om',
  'pa',
  'pe',
  'pf',
  'pg',
  'ph',
  'pk',
  'pl',
  'pm',
  'pn',
  'pr',
  'ps',
  'pt',
  'pw',
  'py',
  'qa',
  're',
  'ro',
  'rs',
  'ru',
  'rw',
  'sa',
  'sb',
  'sc',
  'sd',
  'se',
  'sg',
  'sh',
  'si',
  'sj',
  'sk',
  'sl',
  'sm',
  'sn',
  'so',
  'sr',
  'ss',
  'st',
  'sv',
  'sx',
  'sy',
  'sz',
  'tc',
  'td',
  'tf',
  'tg',
  'th',
  'tj',
  'tk',
  'tl',
  'tm',
  'tn',
  'to',
  'tr',
  'tt',
  'tv',
  'tw',
  'tz',
  'ua',
  'ug',
  'um',
  'us',
  'uy',
  'uz',
  'va',
  'vc',
  've',
  'vg',
  'vi',
  'vn',
  'vu',
  'wf',
  'ws',
  'xk',
  'ye',
  'yt',
  'za',
  'zm',
  'zw',
] as const;
export type CountryId = (typeof country_ids)[number];

export const countries: Record<CountryId, Country> = {
  ad: {
    vector: './maps/ad/vector.svg',
    name: 'Andorra',
    flag: './flags/ad.svg',
  },
  ae: {
    vector: './maps/ae/vector.svg',
    name: 'United Arab Emirates',
    flag: './flags/ae.svg',
  },
  af: {
    vector: './maps/af/vector.svg',
    name: 'Afghanistan',
    flag: './flags/af.svg',
  },
  ag: {
    vector: './maps/ag/vector.svg',
    name: 'Antigua and Barbuda',
    flag: './flags/ag.svg',
  },
  ai: {
    vector: './maps/ai/vector.svg',
    name: 'Anguilla',
    flag: './flags/ai.svg',
  },
  al: {
    vector: './maps/al/vector.svg',
    name: 'Albania',
    flag: './flags/al.svg',
  },
  am: {
    vector: './maps/am/vector.svg',
    name: 'Armenia',
    flag: './flags/am.svg',
  },
  ao: {
    vector: './maps/ao/vector.svg',
    name: 'Angola',
    flag: './flags/ao.svg',
  },
  aq: {
    vector: './maps/aq/vector.svg',
    name: 'Antarctica',
    flag: './flags/aq.svg',
  },
  ar: {
    vector: './maps/ar/vector.svg',
    name: 'Argentina',
    flag: './flags/ar.svg',
  },
  as: {
    vector: './maps/as/vector.svg',
    name: 'American Samoa',
    flag: './flags/as.svg',
  },
  at: {
    vector: './maps/at/vector.svg',
    name: 'Austria',
    flag: './flags/at.svg',
  },
  au: {
    vector: './maps/au/vector.svg',
    name: 'Australia',
    flag: './flags/au.svg',
  },
  aw: {
    vector: './maps/aw/vector.svg',
    name: 'Aruba',
    flag: './flags/aw.svg',
  },
  ax: {
    vector: './maps/ax/vector.svg',
    name: 'Åland Islands',
    flag: './flags/ax.svg',
  },
  az: {
    vector: './maps/az/vector.svg',
    name: 'Azerbaijan',
    flag: './flags/az.svg',
  },
  ba: {
    vector: './maps/ba/vector.svg',
    name: 'Bosnia and Herzegovina',
    flag: './flags/ba.svg',
  },
  bb: {
    vector: './maps/bb/vector.svg',
    name: 'Barbados',
    flag: './flags/bb.svg',
  },
  bd: {
    vector: './maps/bd/vector.svg',
    name: 'Bangladesh',
    flag: './flags/bd.svg',
  },
  be: {
    vector: './maps/be/vector.svg',
    name: 'Belgium',
    flag: './flags/be.svg',
  },
  bf: {
    vector: './maps/bf/vector.svg',
    name: 'Burkina Faso',
    flag: './flags/bf.svg',
  },
  bg: {
    vector: './maps/bg/vector.svg',
    name: 'Bulgaria',
    flag: './flags/bg.svg',
  },
  bh: {
    vector: './maps/bh/vector.svg',
    name: 'Bahrain',
    flag: './flags/bh.svg',
  },
  bi: {
    vector: './maps/bi/vector.svg',
    name: 'Burundi',
    flag: './flags/bi.svg',
  },
  bj: {
    vector: './maps/bj/vector.svg',
    name: 'Benin',
    flag: './flags/bj.svg',
  },
  bl: {
    vector: './maps/bl/vector.svg',
    name: 'Saint Barthélemy',
    flag: './flags/bl.svg',
  },
  bm: {
    vector: './maps/bm/vector.svg',
    name: 'Bermuda',
    flag: './flags/bm.svg',
  },
  bn: {
    vector: './maps/bn/vector.svg',
    name: 'Brunei Darussalam',
    flag: './flags/bn.svg',
  },
  bo: {
    vector: './maps/bo/vector.svg',
    name: 'Bolivia',
    other_names: ['Plurinational State of Bolivia'],
    flag: './flags/bo.svg',
  },
  bq: {
    vector: './maps/bq/vector.svg',
    name: 'Caribbean Netherlands',
    flag: './flags/bq.svg',
  },
  br: {
    vector: './maps/br/vector.svg',
    name: 'Brazil',
    flag: './flags/br.svg',
  },
  bs: {
    vector: './maps/bs/vector.svg',
    name: 'Bahamas',
    flag: './flags/bs.svg',
  },
  bt: {
    vector: './maps/bt/vector.svg',
    name: 'Bhutan',
    flag: './flags/bt.svg',
  },
  bv: {
    vector: './maps/bv/vector.svg',
    name: 'Bouvet Island',
    flag: './flags/bv.svg',
  },
  bw: {
    vector: './maps/bw/vector.svg',
    name: 'Botswana',
    flag: './flags/bw.svg',
  },
  by: {
    vector: './maps/by/vector.svg',
    name: 'Belarus',
    flag: './flags/by.svg',
  },
  bz: {
    vector: './maps/bz/vector.svg',
    name: 'Belize',
    flag: './flags/bz.svg',
  },
  ca: {
    vector: './maps/ca/vector.svg',
    name: 'Canada',
    flag: './flags/ca.svg',
  },
  cc: {
    vector: './maps/cc/vector.svg',
    name: 'Cocos (Keeling) Islands',
    flag: './flags/cc.svg',
  },
  cd: {
    vector: './maps/cd/vector.svg',
    name: 'Congo',
    other_names: ['The Democratic Republic of the Congo', 'DRC'],
    flag: './flags/cd.svg',
  },
  cf: {
    vector: './maps/cf/vector.svg',
    name: 'Central African Republic',
    flag: './flags/cf.svg',
  },
  cg: {
    vector: './maps/cg/vector.svg',
    name: 'Republic of the Congo',
    flag: './flags/cg.svg',
  },
  ch: {
    vector: './maps/ch/vector.svg',
    name: 'Switzerland',
    flag: './flags/ch.svg',
  },
  ci: {
    vector: './maps/ci/vector.svg',
    name: "C\u00f4te d'Ivoire",
    flag: './flags/ci.svg',
  },
  ck: {
    vector: './maps/ck/vector.svg',
    name: 'Cook Islands',
    flag: './flags/ck.svg',
  },
  cl: {
    vector: './maps/cl/vector.svg',
    name: 'Chile',
    flag: './flags/cl.svg',
  },
  cm: {
    vector: './maps/cm/vector.svg',
    name: 'Cameroon',
    flag: './flags/cm.svg',
  },
  cn: {
    vector: './maps/cn/vector.svg',
    name: 'China',
    other_names: ["People's Republic of China"],
    flag: './flags/cn.svg',
  },
  co: {
    vector: './maps/co/vector.svg',
    name: 'Colombia',
    flag: './flags/co.svg',
  },
  cr: {
    vector: './maps/cr/vector.svg',
    name: 'Costa Rica',
    flag: './flags/cr.svg',
  },
  cu: {
    vector: './maps/cu/vector.svg',
    name: 'Cuba',
    flag: './flags/cu.svg',
  },
  cv: {
    vector: './maps/cv/vector.svg',
    name: 'Cape Verde',
    flag: './flags/cv.svg',
  },
  cw: {
    vector: './maps/cw/vector.svg',
    name: 'Cura\u00e7ao',
    flag: './flags/cw.svg',
  },
  cx: {
    vector: './maps/cx/vector.svg',
    name: 'Christmas Island',
    flag: './flags/cx.svg',
  },
  cy: {
    vector: './maps/cy/vector.svg',
    name: 'Cyprus',
    flag: './flags/cy.svg',
  },
  cz: {
    vector: './maps/cz/vector.svg',
    name: 'Czech Republic',
    flag: './flags/cz.svg',
  },
  de: {
    vector: './maps/de/vector.svg',
    name: 'Germany',
    flag: './flags/de.svg',
  },
  dj: {
    vector: './maps/dj/vector.svg',
    name: 'Djibouti',
    flag: './flags/dj.svg',
  },
  dk: {
    vector: './maps/dk/vector.svg',
    name: 'Denmark',
    flag: './flags/dk.svg',
  },
  dm: {
    vector: './maps/dm/vector.svg',
    name: 'Dominica',
    flag: './flags/dm.svg',
  },
  do: {
    vector: './maps/do/vector.svg',
    name: 'Dominican Republic',
    flag: './flags/do.svg',
  },
  dz: {
    vector: './maps/dz/vector.svg',
    name: 'Algeria',
    flag: './flags/dz.svg',
  },
  ec: {
    vector: './maps/ec/vector.svg',
    name: 'Ecuador',
    flag: './flags/ec.svg',
  },
  ee: {
    vector: './maps/ee/vector.svg',
    name: 'Estonia',
    flag: './flags/ee.svg',
  },
  eg: {
    vector: './maps/eg/vector.svg',
    name: 'Egypt',
    flag: './flags/eg.svg',
  },
  eh: {
    vector: './maps/eh/vector.svg',
    name: 'Western Sahara',
    flag: './flags/eh.svg',
  },
  er: {
    vector: './maps/er/vector.svg',
    name: 'Eritrea',
    flag: './flags/er.svg',
  },
  es: {
    vector: './maps/es/vector.svg',
    name: 'Spain',
    flag: './flags/es.svg',
  },
  et: {
    vector: './maps/et/vector.svg',
    name: 'Ethiopia',
    flag: './flags/et.svg',
  },
  eu: {
    vector: './maps/eu/vector.svg',
    name: 'Europe',
    flag: './flags/eu.svg',
  },
  fi: {
    vector: './maps/fi/vector.svg',
    name: 'Finland',
    flag: './flags/fi.svg',
  },
  fj: {
    vector: './maps/fj/vector.svg',
    name: 'Fiji',
    flag: './flags/fj.svg',
  },
  fk: {
    vector: './maps/fk/vector.svg',
    name: 'Falkland Islands (Malvinas)',
    flag: './flags/fk.svg',
  },
  fm: {
    vector: './maps/fm/vector.svg',
    name: 'Micronesia',
    other_names: ['Federated States of Micronesia'],
    flag: './flags/fm.svg',
  },
  fo: {
    vector: './maps/fo/vector.svg',
    name: 'Faroe Islands',
    flag: './flags/fo.svg',
  },
  fr: {
    vector: './maps/fr/vector.svg',
    name: 'France',
    flag: './flags/fr.svg',
  },
  ga: {
    vector: './maps/ga/vector.svg',
    name: 'Gabon',
    flag: './flags/ga.svg',
  },
  gb: {
    vector: './maps/gb/vector.svg',
    name: 'United Kingdom',
    flag: './flags/gb.svg',
  },
  'gb-eng': {
    vector: './maps/gb-eng/vector.svg',
    name: 'England',
    flag: './flags/gb-eng.svg',
  },
  'gb-nir': {
    vector: './maps/gb-nir/vector.svg',
    name: 'Northern Ireland',
    flag: './flags/gb-nir.svg',
  },
  'gb-sct': {
    vector: './maps/gb-sct/vector.svg',
    name: 'Scotland',
    flag: './flags/gb-sct.svg',
  },
  'gb-wls': {
    vector: './maps/gb-wls/vector.svg',
    name: 'Wales',
    flag: './flags/gb-wls.svg',
  },
  gd: {
    vector: './maps/gd/vector.svg',
    name: 'Grenada',
    flag: './flags/gd.svg',
  },
  ge: {
    vector: './maps/ge/vector.svg',
    name: 'Georgia',
    flag: './flags/ge.svg',
  },
  gf: {
    vector: './maps/gf/vector.svg',
    name: 'French Guiana',
    flag: './flags/gf.svg',
  },
  gg: {
    vector: './maps/gg/vector.svg',
    name: 'Guernsey',
    flag: './flags/gg.svg',
  },
  gh: {
    vector: './maps/gh/vector.svg',
    name: 'Ghana',
    flag: './flags/gh.svg',
  },
  gi: {
    vector: './maps/gi/vector.svg',
    name: 'Gibraltar',
    flag: './flags/gi.svg',
  },
  gl: {
    vector: './maps/gl/vector.svg',
    name: 'Greenland',
    flag: './flags/gl.svg',
  },
  gm: {
    vector: './maps/gm/vector.svg',
    name: 'Gambia',
    flag: './flags/gm.svg',
  },
  gn: {
    vector: './maps/gn/vector.svg',
    name: 'Guinea',
    flag: './flags/gn.svg',
  },
  gp: {
    vector: './maps/gp/vector.svg',
    name: 'Guadeloupe',
    flag: './flags/gp.svg',
  },
  gq: {
    vector: './maps/gq/vector.svg',
    name: 'Equatorial Guinea',
    flag: './flags/gq.svg',
  },
  gr: {
    vector: './maps/gr/vector.svg',
    name: 'Greece',
    flag: './flags/gr.svg',
  },
  gs: {
    vector: './maps/gs/vector.svg',
    name: 'South Georgia and the South Sandwich Islands',
    flag: './flags/gs.svg',
  },
  gt: {
    vector: './maps/gt/vector.svg',
    name: 'Guatemala',
    flag: './flags/gt.svg',
  },
  gu: {
    vector: './maps/gu/vector.svg',
    name: 'Guam',
    flag: './flags/gu.svg',
  },
  gw: {
    vector: './maps/gw/vector.svg',
    name: 'Guinea-Bissau',
    flag: './flags/gw.svg',
  },
  gy: {
    vector: './maps/gy/vector.svg',
    name: 'Guyana',
    flag: './flags/gy.svg',
  },
  hk: {
    vector: './maps/hk/vector.svg',
    name: 'Hong Kong',
    flag: './flags/hk.svg',
  },
  hm: {
    vector: './maps/hm/vector.svg',
    name: 'Heard Island and McDonald Islands',
    flag: './flags/hm.svg',
  },
  hn: {
    vector: './maps/hn/vector.svg',
    name: 'Honduras',
    flag: './flags/hn.svg',
  },
  hr: {
    vector: './maps/hr/vector.svg',
    name: 'Croatia',
    flag: './flags/hr.svg',
  },
  ht: {
    vector: './maps/ht/vector.svg',
    name: 'Haiti',
    flag: './flags/ht.svg',
  },
  hu: {
    vector: './maps/hu/vector.svg',
    name: 'Hungary',
    flag: './flags/hu.svg',
  },
  id: {
    vector: './maps/id/vector.svg',
    name: 'Indonesia',
    flag: './flags/id.svg',
  },
  ie: {
    vector: './maps/ie/vector.svg',
    name: 'Ireland',
    flag: './flags/ie.svg',
  },
  il: {
    vector: './maps/il/vector.svg',
    name: 'Israel',
    flag: './flags/il.svg',
  },
  im: {
    vector: './maps/im/vector.svg',
    name: 'Isle of Man',
    flag: './flags/im.svg',
  },
  in: {
    vector: './maps/in/vector.svg',
    name: 'India',
    flag: './flags/in.svg',
  },
  io: {
    vector: './maps/io/vector.svg',
    name: 'British Indian Ocean Territory',
    flag: './flags/io.svg',
  },
  iq: {
    vector: './maps/iq/vector.svg',
    name: 'Iraq',
    flag: './flags/iq.svg',
  },
  ir: {
    vector: './maps/ir/vector.svg',
    name: 'Iran, Islamic Republic of',
    flag: './flags/ir.svg',
  },
  is: {
    vector: './maps/is/vector.svg',
    name: 'Iceland',
    flag: './flags/is.svg',
  },
  it: {
    vector: './maps/it/vector.svg',
    name: 'Italy',
    flag: './flags/it.svg',
  },
  je: {
    vector: './maps/je/vector.svg',
    name: 'Jersey',
    flag: './flags/je.svg',
  },
  jm: {
    vector: './maps/jm/vector.svg',
    name: 'Jamaica',
    flag: './flags/jm.svg',
  },
  jo: {
    vector: './maps/jo/vector.svg',
    name: 'Jordan',
    flag: './flags/jo.svg',
  },
  jp: {
    vector: './maps/jp/vector.svg',
    name: 'Japan',
    flag: './flags/jp.svg',
  },
  ke: {
    vector: './maps/ke/vector.svg',
    name: 'Kenya',
    flag: './flags/ke.svg',
  },
  kg: {
    vector: './maps/kg/vector.svg',
    name: 'Kyrgyzstan',
    flag: './flags/kg.svg',
  },
  kh: {
    vector: './maps/kh/vector.svg',
    name: 'Cambodia',
    flag: './flags/kh.svg',
  },
  ki: {
    vector: './maps/ki/vector.svg',
    name: 'Kiribati',
    flag: './flags/ki.svg',
  },
  km: {
    vector: './maps/km/vector.svg',
    name: 'Comoros',
    flag: './flags/km.svg',
  },
  kn: {
    vector: './maps/kn/vector.svg',
    name: 'Saint Kitts and Nevis',
    flag: './flags/kn.svg',
  },
  kp: {
    vector: './maps/kp/vector.svg',
    name: 'North Korea',
    other_names: ["Democratic People's Republic of Korea"],
    flag: './flags/kp.svg',
  },
  kr: {
    vector: './maps/kr/vector.svg',
    name: 'South Korea',
    other_names: ['Republic of Korea'],
    flag: './flags/kr.svg',
  },
  kw: {
    vector: './maps/kw/vector.svg',
    name: 'Kuwait',
    flag: './flags/kw.svg',
  },
  ky: {
    vector: './maps/ky/vector.svg',
    name: 'Cayman Islands',
    flag: './flags/ky.svg',
  },
  kz: {
    vector: './maps/kz/vector.svg',
    name: 'Kazakhstan',
    flag: './flags/kz.svg',
  },
  la: {
    vector: './maps/la/vector.svg',
    name: 'Laos',
    flag: './flags/la.svg',
  },
  lb: {
    vector: './maps/lb/vector.svg',
    name: 'Lebanon',
    flag: './flags/lb.svg',
  },
  lc: {
    vector: './maps/lc/vector.svg',
    name: 'Saint Lucia',
    flag: './flags/lc.svg',
  },
  li: {
    vector: './maps/li/vector.svg',
    name: 'Liechtenstein',
    flag: './flags/li.svg',
  },
  lk: {
    vector: './maps/lk/vector.svg',
    name: 'Sri Lanka',
    flag: './flags/lk.svg',
  },
  lr: {
    vector: './maps/lr/vector.svg',
    name: 'Liberia',
    flag: './flags/lr.svg',
  },
  ls: {
    vector: './maps/ls/vector.svg',
    name: 'Lesotho',
    flag: './flags/ls.svg',
  },
  lt: {
    vector: './maps/lt/vector.svg',
    name: 'Lithuania',
    flag: './flags/lt.svg',
  },
  lu: {
    vector: './maps/lu/vector.svg',
    name: 'Luxembourg',
    flag: './flags/lu.svg',
  },
  lv: {
    vector: './maps/lv/vector.svg',
    name: 'Latvia',
    flag: './flags/lv.svg',
  },
  ly: {
    vector: './maps/ly/vector.svg',
    name: 'Libya',
    flag: './flags/ly.svg',
  },
  ma: {
    vector: './maps/ma/vector.svg',
    name: 'Morocco',
    flag: './flags/ma.svg',
  },
  mc: {
    vector: './maps/mc/vector.svg',
    name: 'Monaco',
    flag: './flags/mc.svg',
  },
  md: {
    vector: './maps/md/vector.svg',
    name: 'Moldova, Republic of',
    flag: './flags/md.svg',
  },
  me: {
    vector: './maps/me/vector.svg',
    name: 'Montenegro',
    flag: './flags/me.svg',
  },
  mf: {
    vector: './maps/mf/vector.svg',
    name: 'Saint Martin',
    flag: './flags/mf.svg',
  },
  mg: {
    vector: './maps/mg/vector.svg',
    name: 'Madagascar',
    flag: './flags/mg.svg',
  },
  mh: {
    vector: './maps/mh/vector.svg',
    name: 'Marshall Islands',
    flag: './flags/mh.svg',
  },
  mk: {
    vector: './maps/mk/vector.svg',
    name: 'North Macedonia',
    flag: './flags/mk.svg',
  },
  ml: {
    vector: './maps/ml/vector.svg',
    name: 'Mali',
    flag: './flags/ml.svg',
  },
  mm: {
    vector: './maps/mm/vector.svg',
    name: 'Myanmar',
    flag: './flags/mm.svg',
  },
  mn: {
    vector: './maps/mn/vector.svg',
    name: 'Mongolia',
    flag: './flags/mn.svg',
  },
  mo: {
    vector: './maps/mo/vector.svg',
    name: 'Macao',
    flag: './flags/mo.svg',
  },
  mp: {
    vector: './maps/mp/vector.svg',
    name: 'Northern Mariana Islands',
    flag: './flags/mp.svg',
  },
  mq: {
    vector: './maps/mq/vector.svg',
    name: 'Martinique',
    flag: './flags/mq.svg',
  },
  mr: {
    vector: './maps/mr/vector.svg',
    name: 'Mauritania',
    flag: './flags/mr.svg',
  },
  ms: {
    vector: './maps/ms/vector.svg',
    name: 'Montserrat',
    flag: './flags/ms.svg',
  },
  mt: {
    vector: './maps/mt/vector.svg',
    name: 'Malta',
    flag: './flags/mt.svg',
  },
  mu: {
    vector: './maps/mu/vector.svg',
    name: 'Mauritius',
    flag: './flags/mu.svg',
  },
  mv: {
    vector: './maps/mv/vector.svg',
    name: 'Maldives',
    flag: './flags/mv.svg',
  },
  mw: {
    vector: './maps/mw/vector.svg',
    name: 'Malawi',
    flag: './flags/mw.svg',
  },
  mx: {
    vector: './maps/mx/vector.svg',
    name: 'Mexico',
    flag: './flags/mx.svg',
  },
  my: {
    vector: './maps/my/vector.svg',
    name: 'Malaysia',
    flag: './flags/my.svg',
  },
  mz: {
    vector: './maps/mz/vector.svg',
    name: 'Mozambique',
    flag: './flags/mz.svg',
  },
  na: {
    vector: './maps/na/vector.svg',
    name: 'Namibia',
    flag: './flags/na.svg',
  },
  nc: {
    vector: './maps/nc/vector.svg',
    name: 'New Caledonia',
    flag: './flags/nc.svg',
  },
  ne: {
    vector: './maps/ne/vector.svg',
    name: 'Niger',
    flag: './flags/ne.svg',
  },
  nf: {
    vector: './maps/nf/vector.svg',
    name: 'Norfolk Island',
    flag: './flags/nf.svg',
  },
  ng: {
    vector: './maps/ng/vector.svg',
    name: 'Nigeria',
    flag: './flags/ng.svg',
  },
  ni: {
    vector: './maps/ni/vector.svg',
    name: 'Nicaragua',
    flag: './flags/ni.svg',
  },
  nl: {
    vector: './maps/nl/vector.svg',
    name: 'Netherlands',
    flag: './flags/nl.svg',
  },
  no: {
    vector: './maps/no/vector.svg',
    name: 'Norway',
    flag: './flags/no.svg',
  },
  np: {
    vector: './maps/np/vector.svg',
    name: 'Nepal',
    flag: './flags/np.svg',
  },
  nr: {
    vector: './maps/nr/vector.svg',
    name: 'Nauru',
    flag: './flags/nr.svg',
  },
  nu: {
    vector: './maps/nu/vector.svg',
    name: 'Niue',
    flag: './flags/nu.svg',
  },
  nz: {
    vector: './maps/nz/vector.svg',
    name: 'New Zealand',
    flag: './flags/nz.svg',
  },
  om: {
    vector: './maps/om/vector.svg',
    name: 'Oman',
    flag: './flags/om.svg',
  },
  pa: {
    vector: './maps/pa/vector.svg',
    name: 'Panama',
    flag: './flags/pa.svg',
  },
  pe: {
    vector: './maps/pe/vector.svg',
    name: 'Peru',
    flag: './flags/pe.svg',
  },
  pf: {
    vector: './maps/pf/vector.svg',
    name: 'French Polynesia',
    flag: './flags/pf.svg',
  },
  pg: {
    vector: './maps/pg/vector.svg',
    name: 'Papua New Guinea',
    flag: './flags/pg.svg',
  },
  ph: {
    vector: './maps/ph/vector.svg',
    name: 'Philippines',
    flag: './flags/ph.svg',
  },
  pk: {
    vector: './maps/pk/vector.svg',
    name: 'Pakistan',
    flag: './flags/pk.svg',
  },
  pl: {
    vector: './maps/pl/vector.svg',
    name: 'Poland',
    flag: './flags/pl.svg',
  },
  pm: {
    vector: './maps/pm/vector.svg',
    name: 'Saint Pierre and Miquelon',
    flag: './flags/pm.svg',
  },
  pn: {
    vector: './maps/pn/vector.svg',
    name: 'Pitcairn',
    flag: './flags/pn.svg',
  },
  pr: {
    vector: './maps/pr/vector.svg',
    name: 'Puerto Rico',
    flag: './flags/pr.svg',
  },
  ps: {
    vector: './maps/ps/vector.svg',
    name: 'Palestine',
    flag: './flags/ps.svg',
  },
  pt: {
    vector: './maps/pt/vector.svg',
    name: 'Portugal',
    flag: './flags/pt.svg',
  },
  pw: {
    vector: './maps/pw/vector.svg',
    name: 'Palau',
    flag: './flags/pw.svg',
  },
  py: {
    vector: './maps/py/vector.svg',
    name: 'Paraguay',
    flag: './flags/py.svg',
  },
  qa: {
    vector: './maps/qa/vector.svg',
    name: 'Qatar',
    flag: './flags/qa.svg',
  },
  re: {
    vector: './maps/re/vector.svg',
    name: 'Réunion',
    flag: './flags/re.svg',
  },
  ro: {
    vector: './maps/ro/vector.svg',
    name: 'Romania',
    flag: './flags/ro.svg',
  },
  rs: {
    vector: './maps/rs/vector.svg',
    name: 'Serbia',
    flag: './flags/rs.svg',
  },
  ru: {
    vector: './maps/ru/vector.svg',
    name: 'Russian Federation',
    flag: './flags/ru.svg',
  },
  rw: {
    vector: './maps/rw/vector.svg',
    name: 'Rwanda',
    flag: './flags/rw.svg',
  },
  sa: {
    vector: './maps/sa/vector.svg',
    name: 'Saudi Arabia',
    flag: './flags/sa.svg',
  },
  sb: {
    vector: './maps/sb/vector.svg',
    name: 'Solomon Islands',
    flag: './flags/sb.svg',
  },
  sc: {
    vector: './maps/sc/vector.svg',
    name: 'Seychelles',
    flag: './flags/sc.svg',
  },
  sd: {
    vector: './maps/sd/vector.svg',
    name: 'Sudan',
    flag: './flags/sd.svg',
  },
  se: {
    vector: './maps/se/vector.svg',
    name: 'Sweden',
    flag: './flags/se.svg',
  },
  sg: {
    vector: './maps/sg/vector.svg',
    name: 'Singapore',
    flag: './flags/sg.svg',
  },
  sh: {
    vector: './maps/sh/vector.svg',
    name: 'Saint Helena',
    flag: './flags/sh.svg',
  },
  si: {
    vector: './maps/si/vector.svg',
    name: 'Slovenia',
    flag: './flags/si.svg',
  },
  sj: {
    vector: './maps/sj/vector.svg',
    name: 'Svalbard and Jan Mayen Islands',
    flag: './flags/sj.svg',
  },
  sk: {
    vector: './maps/sk/vector.svg',
    name: 'Slovakia',
    flag: './flags/sk.svg',
  },
  sl: {
    vector: './maps/sl/vector.svg',
    name: 'Sierra Leone',
    flag: './flags/sl.svg',
  },
  sm: {
    vector: './maps/sm/vector.svg',
    name: 'San Marino',
    flag: './flags/sm.svg',
  },
  sn: {
    vector: './maps/sn/vector.svg',
    name: 'Senegal',
    flag: './flags/sn.svg',
  },
  so: {
    vector: './maps/so/vector.svg',
    name: 'Somalia',
    flag: './flags/so.svg',
  },
  sr: {
    vector: './maps/sr/vector.svg',
    name: 'Suriname',
    flag: './flags/sr.svg',
  },
  ss: {
    vector: './maps/ss/vector.svg',
    name: 'South Sudan',
    flag: './flags/ss.svg',
  },
  st: {
    vector: './maps/st/vector.svg',
    name: 'Sao Tome and Principe',
    flag: './flags/st.svg',
  },
  sv: {
    vector: './maps/sv/vector.svg',
    name: 'El Salvador',
    flag: './flags/sv.svg',
  },
  sx: {
    vector: './maps/sx/vector.svg',
    name: 'Sint Maarten (Dutch part)',
    flag: './flags/sx.svg',
  },
  sy: {
    vector: './maps/sy/vector.svg',
    name: 'Syrian Arab Republic',
    flag: './flags/sy.svg',
  },
  sz: {
    vector: './maps/sz/vector.svg',
    name: 'Kingdom of Eswatini',
    flag: './flags/sz.svg',
  },
  tc: {
    vector: './maps/tc/vector.svg',
    name: 'Turks and Caicos Islands',
    flag: './flags/tc.svg',
  },
  td: {
    vector: './maps/td/vector.svg',
    name: 'Chad',
    flag: './flags/td.svg',
  },
  tf: {
    vector: './maps/tf/vector.svg',
    name: 'French Southern Territories',
    flag: './flags/tf.svg',
  },
  tg: {
    vector: './maps/tg/vector.svg',
    name: 'Togo',
    flag: './flags/tg.svg',
  },
  th: {
    vector: './maps/th/vector.svg',
    name: 'Thailand',
    flag: './flags/th.svg',
  },
  tj: {
    vector: './maps/tj/vector.svg',
    name: 'Tajikistan',
    flag: './flags/tj.svg',
  },
  tk: {
    vector: './maps/tk/vector.svg',
    name: 'Tokelau',
    flag: './flags/tk.svg',
  },
  tl: {
    vector: './maps/tl/vector.svg',
    name: 'Timor-Leste',
    flag: './flags/tl.svg',
  },
  tm: {
    vector: './maps/tm/vector.svg',
    name: 'Turkmenistan',
    flag: './flags/tm.svg',
  },
  tn: {
    vector: './maps/tn/vector.svg',
    name: 'Tunisia',
    flag: './flags/tn.svg',
  },
  to: {
    vector: './maps/to/vector.svg',
    name: 'Tonga',
    flag: './flags/to.svg',
  },
  tr: {
    vector: './maps/tr/vector.svg',
    name: 'Republic of Türkiye',
    flag: './flags/tr.svg',
  },
  tt: {
    vector: './maps/tt/vector.svg',
    name: 'Trinidad and Tobago',
    flag: './flags/tt.svg',
  },
  tv: {
    vector: './maps/tv/vector.svg',
    name: 'Tuvalu',
    flag: './flags/tv.svg',
  },
  tw: {
    vector: './maps/tw/vector.svg',
    name: 'Taiwan',
    other_names: ['Taiwan, Republic of China'],
    flag: './flags/tw.svg',
  },
  tz: {
    vector: './maps/tz/vector.svg',
    name: 'Tanzania, United Republic of',
    flag: './flags/tz.svg',
  },
  ua: {
    vector: './maps/ua/vector.svg',
    name: 'Ukraine',
    flag: './flags/ua.svg',
  },
  ug: {
    vector: './maps/ug/vector.svg',
    name: 'Uganda',
    flag: './flags/ug.svg',
  },
  um: {
    vector: './maps/um/vector.svg',
    name: 'US Minor Outlying Islands',
    flag: './flags/um.svg',
  },
  us: {
    vector: './maps/us/vector.svg',
    name: 'United States',
    flag: './flags/us.svg',
  },
  uy: {
    vector: './maps/uy/vector.svg',
    name: 'Uruguay',
    flag: './flags/uy.svg',
  },
  uz: {
    vector: './maps/uz/vector.svg',
    name: 'Uzbekistan',
    flag: './flags/uz.svg',
  },
  va: {
    vector: './maps/va/vector.svg',
    name: 'Vatican City',
    other_names: ['Holy See'],
    flag: './flags/va.svg',
  },
  vc: {
    vector: './maps/vc/vector.svg',
    name: 'Saint Vincent and the Grenadines',
    flag: './flags/vc.svg',
  },
  ve: {
    vector: './maps/ve/vector.svg',
    name: 'Venezuela',
    other_names: ['Bolivarian Republic of Venezuela'],
    flag: './flags/ve.svg',
  },
  vg: {
    vector: './maps/vg/vector.svg',
    name: 'Virgin Islands, British',
    flag: './flags/vg.svg',
  },
  vi: {
    vector: './maps/vi/vector.svg',
    name: 'Virgin Islands, U.S.',
    flag: './flags/vi.svg',
  },
  vn: {
    vector: './maps/vn/vector.svg',
    name: 'Vietnam',
    flag: './flags/vn.svg',
  },
  vu: {
    vector: './maps/vu/vector.svg',
    name: 'Vanuatu',
    flag: './flags/vu.svg',
  },
  wf: {
    vector: './maps/wf/vector.svg',
    name: 'Wallis and Futuna Islands',
    flag: './flags/wf.svg',
  },
  ws: {
    vector: './maps/ws/vector.svg',
    name: 'Samoa',
    flag: './flags/ws.svg',
  },
  xk: {
    vector: './maps/xk/vector.svg',
    name: 'Kosovo',
    flag: './flags/xk.svg',
  },
  ye: {
    vector: './maps/ye/vector.svg',
    name: 'Yemen',
    flag: './flags/ye.svg',
  },
  yt: {
    vector: './maps/yt/vector.svg',
    name: 'Mayotte',
    flag: './flags/yt.svg',
  },
  za: {
    vector: './maps/za/vector.svg',
    name: 'South Africa',
    flag: './flags/za.svg',
  },
  zm: {
    vector: './maps/zm/vector.svg',
    name: 'Zambia',
    flag: './flags/zm.svg',
  },
  zw: {
    vector: './maps/zw/vector.svg',
    name: 'Zimbabwe',
    flag: './flags/zw.svg',
  },
};
